"""ABI JSON → Python source emitter.

Build-time only; the emitted code imports :mod:`aleo.codegen.runtime` for
parsing and formatting.  The ABI shape this consumes is the ``aleo-abi``
output: struct = ``{path: [Name], fields: [{name, ty}]}``, record fields add
``mode``, mapping = ``{name, key: ty, value: ty}``, and ``ty`` is either
``{"Primitive": ...}`` or ``{"Struct": {"path": [...], "program": ...}}``.
"""
from __future__ import annotations

from dataclasses import dataclass
from typing import Any, Callable


@dataclass(frozen=True)
class PyType:
    """How one ABI type appears in emitted Python.

    ``annotation`` is the type annotation; ``encode_expr``/``decode_expr``
    map a value expression to the encoding/decoding expression emitted into
    ``to_plaintext``/``from_decoded`` bodies.
    """

    annotation: str
    encode_expr: Callable[[str], str]
    decode_expr: Callable[[str], str]


def resolve_ty(ty: Any) -> PyType:
    """Map an ABI ``ty`` tree to its emitted-Python representation."""
    if isinstance(ty, dict) and "Primitive" in ty:
        prim = ty["Primitive"]
        if isinstance(prim, dict):
            width = prim.get("UInt") or prim.get("Int")
            if width is None:
                raise ValueError(f"Unsupported primitive: {prim!r}")
            suffix = width.lower()
            return PyType("int", lambda e, s=suffix: f"fmt_int({e}, '{s}')", lambda e: e)
        if prim == "Boolean":
            return PyType("bool", lambda e: f"fmt_bool({e})", lambda e: e)
        if prim == "Address":
            return PyType("str", lambda e: f"fmt_address({e})", lambda e: e)
        if prim in ("Field", "Group", "Scalar"):
            suffix = prim.lower()
            return PyType("str", lambda e, s=suffix: f"fmt_fieldlike({e}, '{s}')", lambda e: e)
        raise ValueError(f"Unsupported primitive: {prim!r}")
    if isinstance(ty, dict) and "Struct" in ty:
        name = ty["Struct"]["path"][-1]
        return PyType(
            name,
            lambda e: f"{e}.to_plaintext()",
            lambda e, n=name: f"{n}.from_decoded({e})",
        )
    raise ValueError(f"Unsupported ABI type: {ty!r}")


def emit_struct(struct: dict[str, Any]) -> str:
    """Emit one struct as a frozen dataclass with encode/decode methods."""
    name = struct["path"][-1]
    fields = struct["fields"]
    lines: list[str] = ["@dataclass(frozen=True)", f"class {name}:"]
    for f in fields:
        lines.append(f"    {f['name']}: {resolve_ty(f['ty']).annotation}")

    # to_plaintext — emitted as a parts list + join (readable generated code).
    lines += ["", "    def to_plaintext(self) -> str:", "        parts = ["]
    for f in fields:
        enc = resolve_ty(f["ty"]).encode_expr("self." + f["name"])
        lines.append(f"            \"{f['name']}: \" + {enc},")
    lines += [
        "        ]",
        "        return \"{ \" + \", \".join(parts) + \" }\"",
    ]

    # from_decoded / from_plaintext.  Subscript expressions are precomputed
    # outside the f-string (no backslashes in f-string expressions on 3.10).
    kwarg_parts: list[str] = []
    for f in fields:
        subscript = "d['" + f["name"] + "']"
        kwarg_parts.append(f"{f['name']}={resolve_ty(f['ty']).decode_expr(subscript)}")
    kwargs = ", ".join(kwarg_parts)
    lines += [
        "",
        "    @classmethod",
        "    def from_decoded(cls, d: dict) -> \"" + name + "\":",
        f"        return cls({kwargs})",
        "",
        "    @classmethod",
        "    def from_plaintext(cls, text: str) -> \"" + name + "\":",
        "        return cls.from_decoded(parse_plaintext(text))",
        "",
    ]
    return "\n".join(lines) + "\n"


# ── Records, mappings, module assembly ───────────────────────────────────────

_HEADER = "# Generated by aleo.codegen — DO NOT EDIT.\n"
_IMPORTS = (
    "from dataclasses import dataclass\n"
    "from typing import Any, Callable, Optional\n"
    "from aleo.codegen.runtime import (parse_plaintext, fmt_int, fmt_bool,"
    " fmt_fieldlike, fmt_address)\n\n"
)


def _struct_deps(struct: dict[str, Any]) -> set[str]:
    deps: set[str] = set()
    for f in struct["fields"]:
        ty = f["ty"]
        if isinstance(ty, dict) and "Struct" in ty:
            deps.add(ty["Struct"]["path"][-1])
    return deps


def _toposort(structs: list[dict[str, Any]]) -> list[dict[str, Any]]:
    """Order structs so nested struct classes are defined before use."""
    by_name = {s["path"][-1]: s for s in structs}
    done: list[dict[str, Any]] = []
    seen: set[str] = set()

    def visit(name: str) -> None:
        if name in seen or name not in by_name:
            return
        seen.add(name)
        for dep in _struct_deps(by_name[name]):
            visit(dep)
        done.append(by_name[name])

    for s in structs:
        visit(s["path"][-1])
    return done


def emit_record(record: dict[str, Any]) -> str:
    """Emit one record as a decode-only frozen dataclass.

    Records are produced by scanners and never hand-constructed, so no
    ``to_plaintext`` is emitted.  The scanner's ``_nonce`` rides along as an
    optional extra field.
    """
    name = record["path"][-1]
    lines = ["@dataclass(frozen=True)", f"class {name}:"]
    for f in record["fields"]:
        lines.append(f"    {f['name']}: {resolve_ty(f['ty']).annotation}")
    lines.append("    _nonce: Optional[str] = None")
    kwarg_parts: list[str] = []
    for f in record["fields"]:
        subscript = "d['" + f["name"] + "']"
        kwarg_parts.append(f"{f['name']}={resolve_ty(f['ty']).decode_expr(subscript)}")
    kwargs = ", ".join(kwarg_parts)
    lines += [
        "",
        "    @classmethod",
        f"    def from_decoded(cls, d: dict) -> \"{name}\":",
        f"        return cls({kwargs}, _nonce=d.get('_nonce'))",
        "",
        "    @classmethod",
        f"    def from_plaintext(cls, text: str) -> \"{name}\":",
        "        return cls.from_decoded(parse_plaintext(text))",
        "",
    ]
    return "\n".join(lines) + "\n"


def emit_module(abi: dict[str, Any]) -> str:
    """Emit a complete generated module for one program's ABI."""
    parts = [_HEADER, _IMPORTS, f"PROGRAM_ID = \"{abi['program']}\"\n\n"]
    for s in _toposort(abi.get("structs", [])):
        parts.append(emit_struct(s))
        parts.append("\n")
    for r in abi.get("records", []):
        parts.append(emit_record(r))
        parts.append("\n")
    dec_entries: list[str] = []
    for m in abi.get("mappings", []):
        v = m["value"]
        if isinstance(v, dict) and "Struct" in v:
            dec_entries.append(f"    \"{m['name']}\": {v['Struct']['path'][-1]}.from_plaintext,")
        else:
            dec_entries.append(f"    \"{m['name']}\": parse_plaintext,")
    parts.append("MAPPING_VALUE_DECODERS: dict[str, Callable[[str], Any]] = {\n"
                 + "\n".join(dec_entries) + "\n}\n")
    return "".join(parts)
