from __future__ import annotations
from typing import List, Mapping, Tuple


class Account:
    @staticmethod
    def random() -> Account: ...
    @staticmethod
    def from_private_key(private_key: PrivateKey) -> Account: ...
    @property
    def private_key(self) -> PrivateKey: ...
    @property
    def view_key(self) -> ViewKey: ...
    @property
    def address(self) -> Address: ...
    def sign(self, message: bytes) -> Signature: ...
    def verify(self, signature: Signature, message: bytes) -> bool: ...
    def decrypt(self, record_ciphertext: RecordCiphertext) -> RecordPlaintext: ...
    def is_owner(self, record_ciphertext: RecordCiphertext) -> bool: ...


class Address:
    @staticmethod
    def from_string(s: str) -> Address: ...
    @staticmethod
    def from_group(group: Group) -> Address: ...
    @staticmethod
    def from_bytes_le(bytes: bytes) -> Address: ...
    def to_group(self) -> Group: ...
    def to_field(self) -> Field: ...
    def to_bytes_le(self) -> bytes: ...


class Authorization:
    @staticmethod
    def from_json(json: str) -> Authorization: ...
    def to_json(self) -> str: ...
    @staticmethod
    def from_bytes(bytes: bytes) -> Authorization: ...
    def bytes(self) -> bytes: ...


class BHP256:
    def __new__(cls) -> BHP256: ...
    @staticmethod
    def setup(domain_separator: str) -> BHP256: ...
    def hash(self, input: List[bool]) -> Field: ...
    def hash_to_group(self, input: List[bool]) -> Group: ...
    def commit(self, input: List[bool], randomizer: Scalar) -> Field: ...
    def commit_to_group(self, input: List[bool], randomizer: Scalar) -> Group: ...


class BHP512:
    def __new__(cls) -> BHP512: ...
    @staticmethod
    def setup(domain_separator: str) -> BHP512: ...
    def hash(self, input: List[bool]) -> Field: ...
    def hash_to_group(self, input: List[bool]) -> Group: ...
    def commit(self, input: List[bool], randomizer: Scalar) -> Field: ...
    def commit_to_group(self, input: List[bool], randomizer: Scalar) -> Group: ...


class BHP768:
    def __new__(cls) -> BHP768: ...
    @staticmethod
    def setup(domain_separator: str) -> BHP768: ...
    def hash(self, input: List[bool]) -> Field: ...
    def hash_to_group(self, input: List[bool]) -> Group: ...
    def commit(self, input: List[bool], randomizer: Scalar) -> Field: ...
    def commit_to_group(self, input: List[bool], randomizer: Scalar) -> Group: ...


class BHP1024:
    def __new__(cls) -> BHP1024: ...
    @staticmethod
    def setup(domain_separator: str) -> BHP1024: ...
    def hash(self, input: List[bool]) -> Field: ...
    def hash_to_group(self, input: List[bool]) -> Group: ...
    def commit(self, input: List[bool], randomizer: Scalar) -> Field: ...
    def commit_to_group(self, input: List[bool], randomizer: Scalar) -> Group: ...


class Boolean:
    def __new__(cls, b: bool) -> Boolean: ...


class Ciphertext:
    @staticmethod
    def from_string(s: str) -> Ciphertext: ...
    def decrypt(self, view_key: ViewKey, nonce: Group) -> Plaintext: ...
    def decrypt_symmetric(self, plaintext_view_key: Field) -> Plaintext: ...


class Credits:
    def __new__(cls, value: float) -> Credits: ...
    def micro(self) -> MicroCredits: ...


class ComputeKey:
    @property
    def address(self) -> Address: ...
    def pk_sig(self) -> Group: ...
    def pr_sig(self) -> Group: ...
    def sk_prf(self) -> Scalar: ...


class Encryptor:
    @staticmethod
    def encrypt_private_key_with_secret(private_key: PrivateKey, secret: str) -> Ciphertext: ...
    @staticmethod
    def decrypt_private_key_with_secret(ciphertext: Ciphertext, secret: str) -> PrivateKey: ...


class Execution:
    @property
    def execution_id(self) -> Field: ...
    @staticmethod
    def from_json(json: str) -> Execution: ...
    def to_json(self) -> str: ...
    @staticmethod
    def from_bytes(bytes: bytes) -> Execution: ...
    def bytes(self) -> bytes: ...


class Fee:
    def is_fee_private(self) -> bool: ...
    def is_fee_public(self) -> bool: ...
    @property
    def payer(self) -> Address | None: ...
    @property
    def transition(self) -> Transition: ...
    @staticmethod
    def from_json(json: str) -> Fee: ...
    def to_json(self) -> str: ...
    @staticmethod
    def from_bytes(bytes: bytes) -> Fee: ...
    def bytes(self) -> bytes: ...


class Field:
    @staticmethod
    def random() -> Field: ...
    @staticmethod
    def from_string(s: str) -> Field: ...
    @staticmethod
    def domain_separator(domain: str) -> Field: ...
    @staticmethod
    def from_u128(u128: int) -> Field: ...
    @staticmethod
    def zero() -> Field: ...
    @staticmethod
    def one() -> Field: ...
    @staticmethod
    def from_bits_le(bits: List[bool]) -> Field: ...
    @staticmethod
    def from_bytes_le(bytes: bytes) -> Field: ...
    def to_bytes_le(self) -> bytes: ...
    def double(self) -> Field: ...
    def add(self, other: Field) -> Field: ...
    def subtract(self, other: Field) -> Field: ...
    def multiply(self, other: Field) -> Field: ...
    def divide(self, other: Field) -> Field: ...
    def pow(self, other: Field) -> Field: ...
    def negate(self) -> Field: ...
    def to_scalar_lossy(self) -> Scalar: ...
    def to_group(self) -> Group: ...
    def __add__(self, other: Field) -> Field: ...
    def __sub__(self, other: Field) -> Field: ...
    def __mul__(self, other: Field) -> Field: ...
    def __truediv__(self, other: Field) -> Field: ...
    def __pow__(self, other: Field) -> Field: ...
    def __neg__(self) -> Field: ...
    def to_bits_le(self) -> List[bool]: ...


class GraphKey:
    @staticmethod
    def from_view_key(view_key: ViewKey) -> GraphKey: ...
    @staticmethod
    def from_string(s: str) -> GraphKey: ...
    @property
    def sk_tag(self) -> Field: ...


class Group:
    @staticmethod
    def from_string(s: str) -> Group: ...
    @staticmethod
    def zero() -> Group: ...
    @staticmethod
    def generator() -> Group: ...
    @staticmethod
    def from_field(field: Field) -> Group: ...
    @staticmethod
    def from_bytes_le(bytes: bytes) -> Group: ...
    def to_x_coordinate(self) -> Field: ...
    def to_address(self) -> Address: ...
    def double(self) -> Group: ...
    def to_bytes_le(self) -> bytes: ...
    def add(self, other: Group) -> Group: ...
    def subtract(self, other: Group) -> Group: ...
    def negate(self) -> Group: ...
    def scalar_multiply(self, scalar: Scalar) -> Group: ...
    def __add__(self, other: Group) -> Group: ...
    def __sub__(self, other: Group) -> Group: ...
    def __neg__(self) -> Group: ...
    def __mul__(self, scalar: Scalar) -> Group: ...


class Identifier:
    @staticmethod
    def from_string(s: str) -> Identifier: ...


class I8:
    def __new__(cls, value: int) -> I8: ...
    @staticmethod
    def zero() -> I8: ...
    def __int__(self) -> int: ...


class I16:
    def __new__(cls, value: int) -> I16: ...
    @staticmethod
    def zero() -> I16: ...
    def __int__(self) -> int: ...


class I32:
    def __new__(cls, value: int) -> I32: ...
    @staticmethod
    def zero() -> I32: ...
    def __int__(self) -> int: ...


class I64:
    def __new__(cls, value: int) -> I64: ...
    @staticmethod
    def zero() -> I64: ...
    def __int__(self) -> int: ...


class I128:
    def __new__(cls, value: int) -> I128: ...
    @staticmethod
    def zero() -> I128: ...
    def __int__(self) -> int: ...


class Literal:
    @staticmethod
    def parse(s: str) -> Literal: ...
    @staticmethod
    def from_address(address: Address) -> Literal: ...
    @staticmethod
    def from_field(field: Field) -> Literal: ...
    @staticmethod
    def from_group(group: Group) -> Literal: ...
    @staticmethod
    def from_scalar(scalar: Scalar) -> Literal: ...
    @staticmethod
    def from_signature(signature: Signature) -> Literal: ...
    @staticmethod
    def from_boolean(boolean: Boolean) -> Literal: ...
    @staticmethod
    def from_i8(value: I8) -> Literal: ...
    @staticmethod
    def from_i16(value: I16) -> Literal: ...
    @staticmethod
    def from_i32(value: I32) -> Literal: ...
    @staticmethod
    def from_i64(value: I64) -> Literal: ...
    @staticmethod
    def from_i128(value: I128) -> Literal: ...
    @staticmethod
    def from_u8(value: U8) -> Literal: ...
    @staticmethod
    def from_u16(value: U16) -> Literal: ...
    @staticmethod
    def from_u32(value: U32) -> Literal: ...
    @staticmethod
    def from_u64(value: U64) -> Literal: ...
    @staticmethod
    def from_u128(value: U128) -> Literal: ...
    def type_name(self) -> str: ...


class Locator:
    def __new__(cls, program_id: ProgramID, resource: Identifier) -> Locator: ...
    @staticmethod
    def from_string(s: str) -> Locator: ...
    @property
    def program_id(self) -> ProgramID: ...
    @property
    def name(self) -> Identifier: ...
    @property
    def network(self) -> Identifier: ...
    @property
    def resource(self) -> Identifier: ...


class Network:
    @staticmethod
    def name() -> str: ...
    @staticmethod
    def id() -> int: ...
    @staticmethod
    def hash_psd2(input: List[Field]) -> Field: ...


class MicroCredits:
    def __new__(cls, value: int) -> MicroCredits: ...
    def __int__(self) -> int: ...


class Pedersen64:
    def __new__(cls) -> Pedersen64: ...
    @staticmethod
    def setup(domain_separator: str) -> Pedersen64: ...
    def hash(self, input: List[bool]) -> Field: ...
    def commit(self, input: List[bool], randomizer: Scalar) -> Field: ...
    def commit_to_group(self, input: List[bool], randomizer: Scalar) -> Group: ...


class Pedersen128:
    def __new__(cls) -> Pedersen128: ...
    @staticmethod
    def setup(domain_separator: str) -> Pedersen128: ...
    def hash(self, input: List[bool]) -> Field: ...
    def commit(self, input: List[bool], randomizer: Scalar) -> Field: ...
    def commit_to_group(self, input: List[bool], randomizer: Scalar) -> Group: ...


class Plaintext:
    @staticmethod
    def from_string(s: str) -> Plaintext: ...
    @staticmethod
    def new_literal(literal: Literal) -> Plaintext: ...
    @staticmethod
    def new_struct(kv: List[Tuple[Identifier, Plaintext]]) -> Plaintext: ...
    @staticmethod
    def new_array(kv: List[Plaintext]) -> Plaintext: ...
    def encrypt(self, address: Address, randomizer: Scalar) -> Ciphertext: ...
    def encrypt_symmetric(self, plaintext_view_key: Field) -> Ciphertext: ...
    def is_literal(self) -> bool: ...
    def is_struct(self) -> bool: ...
    def is_array(self) -> bool: ...
    def as_literal(self) -> Literal: ...
    def as_struct(self) -> Mapping[Identifier, Plaintext]: ...
    def as_array(self) -> List[Plaintext]: ...


class Poseidon2:
    def __new__(cls) -> Poseidon2: ...
    @staticmethod
    def setup(domain_separator: str) -> Poseidon2: ...
    def hash(self, input: List[Field]) -> Field: ...
    def hash_many(self, input: List[Field], num_outputs: int) -> List[Field]: ...
    def hash_to_scalar(self, input: List[Field]) -> Scalar: ...
    def hash_to_group(self, input: List[Field]) -> Group: ...


class Poseidon4:
    def __new__(cls) -> Poseidon4: ...
    @staticmethod
    def setup(domain_separator: str) -> Poseidon4: ...
    def hash(self, input: List[Field]) -> Field: ...
    def hash_many(self, input: List[Field], num_outputs: int) -> List[Field]: ...
    def hash_to_scalar(self, input: List[Field]) -> Scalar: ...
    def hash_to_group(self, input: List[Field]) -> Group: ...


class Poseidon8:
    def __new__(cls) -> Poseidon8: ...
    @staticmethod
    def setup(domain_separator: str) -> Poseidon8: ...
    def hash(self, input: List[Field]) -> Field: ...
    def hash_many(self, input: List[Field], num_outputs: int) -> List[Field]: ...
    def hash_to_scalar(self, input: List[Field]) -> Scalar: ...
    def hash_to_group(self, input: List[Field]) -> Group: ...


class PrivateKey:
    @staticmethod
    def random() -> PrivateKey: ...
    @staticmethod
    def from_string(private_key: str) -> PrivateKey: ...
    @staticmethod
    def from_seed(seed: Field) -> PrivateKey: ...
    @property
    def address(self) -> Address: ...
    @property
    def view_key(self) -> ViewKey: ...
    @property
    def compute_key(self) -> ComputeKey: ...
    @property
    def seed(self) -> Field: ...
    def sign(self, message: bytes) -> Signature: ...
    def sk_sig(self) -> Scalar: ...
    def r_sig(self) -> Scalar: ...


class Process:
    @staticmethod
    def load() -> Process: ...
    def add_program(self, program: Program) -> None: ...
    def contains_program(self, program_id: ProgramID) -> bool: ...
    def get_proving_key(self, program_id: ProgramID, function_name: Identifier) -> ProvingKey: ...
    def insert_proving_key(self, program_id: ProgramID, function_name: Identifier, proving_key: ProvingKey) -> None: ...
    def get_verifying_key(self, program_id: ProgramID, function_name: Identifier) -> VerifyingKey: ...
    def insert_verifying_key(self, program_id: ProgramID, function_name: Identifier, verifying_key: VerifyingKey) -> None: ...
    def authorize(self, private_key: PrivateKey, program_id: ProgramID,
                  function_name: Identifier, inputs: List[Value]) -> Authorization: ...
    def authorize_fee_private(self, private_key: PrivateKey, credits: RecordPlaintext, base_fee: int,
                              priority_fee: int, deployment_or_execution_id: Field) -> Authorization: ...
    def authorize_fee_public(self, private_key: PrivateKey, base_fee: int,
                             priority_fee: int, deployment_or_execution_id: Field) -> Authorization: ...
    def execute(self, authorization: Authorization) -> Tuple[Response, Trace]: ...
    def verify_execution(self, execution: Execution) -> None: ...
    def verify_fee(self, fee: Fee, deployment_or_execution_id: Field) -> None: ...
    def execution_cost(self, execution: Execution) -> tuple[int, tuple[int, int]]: ...


class Program:
    @staticmethod
    def from_source(s: str) -> Program: ...
    @staticmethod
    def credits() -> Program: ...
    @property
    def id(self) -> ProgramID: ...
    @property
    def functions(self) -> List[Identifier]: ...
    @property
    def imports(self) -> List[ProgramID]: ...
    @property
    def source(self) -> str: ...


class ProgramID:
    @staticmethod
    def from_string(s: str) -> ProgramID: ...
    @property
    def name(self) -> Identifier: ...
    @property
    def network(self) -> Identifier: ...
    def is_aleo(self) -> bool: ...


class ProvingKey:
    @staticmethod
    def from_string(s: str) -> ProvingKey: ...
    @staticmethod
    def from_bytes(bytes: bytes) -> ProvingKey: ...
    def bytes(self) -> bytes: ...


class Query:
    @staticmethod
    def rest(url: str) -> Query: ...


class RecordCiphertext:
    @staticmethod
    def from_string(s: str) -> RecordCiphertext: ...
    def decrypt(self, view_key: ViewKey) -> RecordPlaintext: ...
    def is_owner(self, view_key: ViewKey) -> bool: ...
    @property
    def nonce(self) -> Group: ...
    def record_view_key(self, view_key: ViewKey) -> Field: ...
    def decrypt_with_record_view_key(self, record_view_key: Field) -> RecordPlaintext: ...
    @staticmethod
    def tag(graph_key: GraphKey, commitment: Field) -> Field: ...


class RecordPlaintext:
    @staticmethod
    def from_string(s: str) -> RecordPlaintext: ...
    @property
    def owner(self) -> str: ...
    @property
    def nonce(self) -> Group: ...
    @property
    def version(self) -> int: ...
    @property
    def microcredits(self) -> int: ...
    def commitment(self, program_id: ProgramID, record_name: Identifier, record_view_key: Field) -> Field: ...
    def record_view_key(self, view_key: ViewKey) -> Field: ...
    def tag(self, graph_key: GraphKey, commitment: Field) -> Field: ...
    def get_member(self, name: str) -> Plaintext: ...
    def serial_number(self, private_key: PrivateKey, program_id: ProgramID,
                      record_identifier: Identifier, record_view_key: Field) -> Field: ...


class Response:
    @property
    def outputs(self) -> List[Value]: ...


class Scalar:
    @staticmethod
    def from_string(s: str) -> Scalar: ...
    @staticmethod
    def zero() -> Scalar: ...
    @staticmethod
    def one() -> Scalar: ...
    @staticmethod
    def from_bytes_le(bytes: bytes) -> Scalar: ...
    def to_bytes_le(self) -> bytes: ...
    def to_field(self) -> Field: ...
    def add(self, other: Scalar) -> Scalar: ...
    def subtract(self, other: Scalar) -> Scalar: ...
    def multiply(self, other: Scalar) -> Scalar: ...
    def divide(self, other: Scalar) -> Scalar: ...
    def __add__(self, other: Scalar) -> Scalar: ...
    def __sub__(self, other: Scalar) -> Scalar: ...
    def __mul__(self, other: Scalar) -> Scalar: ...
    def __truediv__(self, other: Scalar) -> Scalar: ...


class Signature:
    @property
    def challenge(self) -> Scalar: ...
    @property
    def compute_key(self) -> ComputeKey: ...
    @property
    def response(self) -> Scalar: ...
    @staticmethod
    def from_string(s: str) -> Signature: ...
    @staticmethod
    def sign(private_key: PrivateKey, message: bytes) -> Signature: ...
    def verify(self, address: Address, message: bytes) -> bool: ...


class Trace:
    def is_fee(self) -> bool: ...
    def is_fee_private(self) -> bool: ...
    def is_fee_public(self) -> bool: ...
    def transitions(self) -> List[Transition]: ...
    def prove_execution(self, locator: str) -> Execution: ...
    def prove_fee(self) -> Fee: ...
    def prepare(self, query: Query) -> None: ...


class Transaction:
    @staticmethod
    def from_execution(execution: Execution, fee: Fee | None) -> Transaction: ...
    @staticmethod
    def from_json(json: str) -> Transaction: ...
    def to_json(self) -> str: ...
    @staticmethod
    def from_bytes(bytes: bytes) -> Transaction: ...
    def bytes(self) -> bytes: ...


class Transition:
    @property
    def id(self) -> str: ...
    @property
    def program_id(self) -> ProgramID: ...
    @property
    def function_name(self) -> Identifier: ...
    def is_bond_public(self) -> bool: ...
    def is_unbond_public(self) -> bool: ...
    def is_fee_private(self) -> bool: ...
    def is_fee_public(self) -> bool: ...
    def is_split(self) -> bool: ...
    @staticmethod
    def from_json(json: str) -> Transition: ...
    def to_json(self) -> str: ...
    @staticmethod
    def from_bytes(bytes: bytes) -> Transition: ...
    def bytes(self) -> bytes: ...


class U8:
    def __new__(cls, value: int) -> U8: ...
    @staticmethod
    def zero() -> U8: ...
    def __int__(self) -> int: ...


class U16:
    def __new__(cls, value: int) -> U16: ...
    @staticmethod
    def zero() -> U16: ...
    def __int__(self) -> int: ...


class U32:
    def __new__(cls, value: int) -> U32: ...
    @staticmethod
    def zero() -> U32: ...
    def __int__(self) -> int: ...


class U64:
    def __new__(cls, value: int) -> U64: ...
    @staticmethod
    def zero() -> U64: ...
    def __int__(self) -> int: ...


class U128:
    def __new__(cls, value: int) -> U128: ...
    @staticmethod
    def zero() -> U128: ...
    def __int__(self) -> int: ...


class Value:
    @staticmethod
    def parse(s: str) -> Value: ...
    @staticmethod
    def from_literal(literal: Literal) -> Value: ...
    @staticmethod
    def from_record_plaintext(record_plaintext: RecordPlaintext) -> Value: ...


class VerifyingKey:
    @staticmethod
    def from_string(s: str) -> VerifyingKey: ...
    @staticmethod
    def from_bytes(bytes: bytes) -> VerifyingKey: ...
    def bytes(self) -> bytes: ...


class ViewKey:
    def decrypt(self, record_ciphertext: RecordCiphertext) -> RecordPlaintext: ...
    @staticmethod
    def from_string(s: str) -> ViewKey: ...
    def is_owner(self, record_ciphertext: RecordCiphertext) -> bool: ...
    @property
    def address(self) -> Address: ...
    def to_scalar(self) -> Scalar: ...
    def to_field(self) -> Field: ...
