from __future__ import annotations

from typing import Any

class Account:
    @staticmethod
    def random() -> Account: ...
    @staticmethod
    def from_private_key(private_key: PrivateKey) -> Account: ...
    @property
    def private_key(self) -> PrivateKey: ...
    @property
    def view_key(self) -> ViewKey: ...
    @property
    def address(self) -> Address: ...
    def sign(self, message: bytes) -> Signature: ...
    def verify(self, signature: Signature, message: bytes) -> bool: ...
    def decrypt(self, record_ciphertext: RecordCiphertext) -> RecordPlaintext: ...
    def is_owner(self, record_ciphertext: RecordCiphertext) -> bool: ...


class Address:
    @staticmethod
    def from_string(s: str) -> "Address": ...
    @staticmethod
    def from_group(group: "Group") -> "Address": ...
    @staticmethod
    def from_bytes_le(bytes: bytes) -> "Address": ...
    @staticmethod
    def from_program_id(program_id: str) -> "Address": ...
    @staticmethod
    def is_valid(address: str) -> bool: ...
    def to_group(self) -> "Group": ...
    def to_field(self) -> "Field": ...
    def to_bytes_le(self) -> bytes: ...
    def to_bits_le(self) -> list[bool]: ...
    @staticmethod
    def from_bits_le(bits: list[bool]) -> "Address": ...
    def to_fields(self) -> list["Field"]: ...
    @staticmethod
    def from_fields(fields: list["Field"]) -> "Address": ...
    def to_plaintext(self) -> "Plaintext": ...
    def to_scalar_lossy(self) -> "Scalar": ...
    def to_boolean_lossy(self) -> "Boolean": ...
    def to_u8_lossy(self) -> "U8": ...
    def to_u16_lossy(self) -> "U16": ...
    def to_u32_lossy(self) -> "U32": ...
    def to_u64_lossy(self) -> "U64": ...
    def to_u128_lossy(self) -> "U128": ...
    def to_i8_lossy(self) -> "I8": ...
    def to_i16_lossy(self) -> "I16": ...
    def to_i32_lossy(self) -> "I32": ...
    def to_i64_lossy(self) -> "I64": ...
    def to_i128_lossy(self) -> "I128": ...


class Authorization:
    @staticmethod
    def from_json(json: str) -> Authorization: ...
    def to_json(self) -> str: ...
    @staticmethod
    def from_bytes(bytes: bytes) -> Authorization: ...
    def bytes(self) -> bytes: ...
    def to_execution_id(self) -> Field: ...
    def transitions(self) -> list[Transition]: ...
    def function_name(self) -> str: ...
    def is_fee_private(self) -> bool: ...
    def is_fee_public(self) -> bool: ...
    def is_split(self) -> bool: ...
    def __len__(self) -> int: ...
    def replicate(self) -> Authorization: ...
    def insert_transition(self, transition: Transition) -> None: ...


class BHP256:
    def __new__(cls) -> BHP256: ...
    @staticmethod
    def setup(domain_separator: str) -> BHP256: ...
    def hash(self, input: list[bool]) -> Field: ...
    def hash_to_group(self, input: list[bool]) -> Group: ...
    def commit(self, input: list[bool], randomizer: Scalar) -> Field: ...
    def commit_to_group(self, input: list[bool], randomizer: Scalar) -> Group: ...


class BHP512:
    def __new__(cls) -> BHP512: ...
    @staticmethod
    def setup(domain_separator: str) -> BHP512: ...
    def hash(self, input: list[bool]) -> Field: ...
    def hash_to_group(self, input: list[bool]) -> Group: ...
    def commit(self, input: list[bool], randomizer: Scalar) -> Field: ...
    def commit_to_group(self, input: list[bool], randomizer: Scalar) -> Group: ...


class BHP768:
    def __new__(cls) -> BHP768: ...
    @staticmethod
    def setup(domain_separator: str) -> BHP768: ...
    def hash(self, input: list[bool]) -> Field: ...
    def hash_to_group(self, input: list[bool]) -> Group: ...
    def commit(self, input: list[bool], randomizer: Scalar) -> Field: ...
    def commit_to_group(self, input: list[bool], randomizer: Scalar) -> Group: ...


class BHP1024:
    def __new__(cls) -> BHP1024: ...
    @staticmethod
    def setup(domain_separator: str) -> BHP1024: ...
    def hash(self, input: list[bool]) -> Field: ...
    def hash_to_group(self, input: list[bool]) -> Group: ...
    def commit(self, input: list[bool], randomizer: Scalar) -> Field: ...
    def commit_to_group(self, input: list[bool], randomizer: Scalar) -> Group: ...


class Boolean:
    def __new__(cls, b: bool) -> Boolean: ...
    @staticmethod
    def from_string(s: str) -> Boolean: ...
    @staticmethod
    def random() -> Boolean: ...
    @staticmethod
    def from_bytes_le(bytes: bytes) -> Boolean: ...
    @staticmethod
    def from_bits_le(bits: list[bool]) -> Boolean: ...
    def to_bytes_le(self) -> bytes: ...
    def to_bits_le(self) -> list[bool]: ...
    def not_(self) -> Boolean: ...
    def and_(self, other: Boolean) -> Boolean: ...
    def or_(self, other: Boolean) -> Boolean: ...
    def xor(self, other: Boolean) -> Boolean: ...
    def nand(self, other: Boolean) -> Boolean: ...
    def nor(self, other: Boolean) -> Boolean: ...
    def __invert__(self) -> Boolean: ...
    def __and__(self, other: Boolean) -> Boolean: ...
    def __or__(self, other: Boolean) -> Boolean: ...
    def __xor__(self, other: Boolean) -> Boolean: ...
    def __bool__(self) -> bool: ...
    def to_plaintext(self) -> Plaintext: ...
    def to_field(self) -> Field: ...
    def to_scalar(self) -> Scalar: ...
    def to_group(self) -> Group: ...
    def to_address(self) -> Address: ...
    def to_u8(self) -> U8: ...
    def to_u16(self) -> U16: ...
    def to_u32(self) -> U32: ...
    def to_u64(self) -> U64: ...
    def to_u128(self) -> U128: ...
    def to_i8(self) -> I8: ...
    def to_i16(self) -> I16: ...
    def to_i32(self) -> I32: ...
    def to_i64(self) -> I64: ...
    def to_i128(self) -> I128: ...


class Ciphertext:
    @staticmethod
    def from_string(s: str) -> Ciphertext: ...
    def decrypt(self, view_key: ViewKey, nonce: Group) -> Plaintext: ...
    def decrypt_symmetric(self, plaintext_view_key: Field) -> Plaintext: ...
    def decrypt_with_transition_view_key(self, tvk: Field, program: str, function_name: str, index: int) -> Plaintext: ...
    def decrypt_with_transition_info(self, view_key: ViewKey, tpk: Group, program: str, function_name: str, index: int) -> Plaintext: ...


class Credits:
    def __new__(cls, value: float) -> Credits: ...
    def micro(self) -> MicroCredits: ...


class ComputeKey:
    @property
    def address(self) -> Address: ...
    def pk_sig(self) -> Group: ...
    def pr_sig(self) -> Group: ...
    def sk_prf(self) -> Scalar: ...


class DynamicRecord:
    @staticmethod
    def from_string(s: str) -> DynamicRecord: ...
    @staticmethod
    def from_record(record: RecordPlaintext) -> DynamicRecord: ...
    @staticmethod
    def from_bytes(bytes: bytes) -> DynamicRecord: ...
    def to_record(self, owner_is_private: bool) -> RecordPlaintext: ...
    def bytes(self) -> bytes: ...
    def to_fields(self) -> list[Field]: ...
    def to_bits_le(self) -> list[bool]: ...
    @property
    def owner(self) -> Address: ...
    @property
    def root(self) -> Field: ...
    @property
    def nonce(self) -> Group: ...
    def is_hiding(self) -> bool: ...


class Execution:
    @property
    def execution_id(self) -> Field: ...
    @property
    def global_state_root(self) -> str: ...
    def proof(self) -> str | None: ...
    def transitions(self) -> list[Transition]: ...
    @staticmethod
    def from_json(json: str) -> Execution: ...
    def to_json(self) -> str: ...
    @staticmethod
    def from_bytes(bytes: bytes) -> Execution: ...
    def bytes(self) -> bytes: ...


class Fee:
    def is_fee_private(self) -> bool: ...
    def is_fee_public(self) -> bool: ...
    @property
    def payer(self) -> Address | None: ...
    @property
    def transition(self) -> Transition: ...
    @staticmethod
    def from_json(json: str) -> Fee: ...
    def to_json(self) -> str: ...
    @staticmethod
    def from_bytes(bytes: bytes) -> Fee: ...
    def bytes(self) -> bytes: ...


class Field:
    @staticmethod
    def random() -> Field: ...
    @staticmethod
    def from_string(s: str) -> Field: ...
    @staticmethod
    def domain_separator(domain: str) -> Field: ...
    @staticmethod
    def from_u128(u128: int) -> Field: ...
    @staticmethod
    def zero() -> Field: ...
    @staticmethod
    def one() -> Field: ...
    @staticmethod
    def from_bits_le(bits: list[bool]) -> Field: ...
    @staticmethod
    def from_bytes_le(bytes: bytes) -> Field: ...
    def to_bytes_le(self) -> bytes: ...
    def double(self) -> Field: ...
    def add(self, other: Field) -> Field: ...
    def subtract(self, other: Field) -> Field: ...
    def multiply(self, other: Field) -> Field: ...
    def divide(self, other: Field) -> Field: ...
    def pow(self, other: Field) -> Field: ...
    def negate(self) -> Field: ...
    def to_scalar_lossy(self) -> Scalar: ...
    def to_group(self) -> Group: ...
    def __add__(self, other: Field) -> Field: ...
    def __sub__(self, other: Field) -> Field: ...
    def __mul__(self, other: Field) -> Field: ...
    def __truediv__(self, other: Field) -> Field: ...
    def __pow__(self, other: Field) -> Field: ...
    def __neg__(self) -> Field: ...
    def to_bits_le(self) -> list[bool]: ...
    def to_group_lossy(self) -> Group: ...
    def to_address(self) -> Address: ...
    def to_address_lossy(self) -> Address: ...
    def to_boolean(self) -> Boolean: ...
    def to_boolean_lossy(self) -> Boolean: ...
    def to_plaintext(self) -> Plaintext: ...
    def to_u8_lossy(self) -> U8: ...
    def to_u16_lossy(self) -> U16: ...
    def to_u32_lossy(self) -> U32: ...
    def to_u64_lossy(self) -> U64: ...
    def to_u128_lossy(self) -> U128: ...
    def to_i8_lossy(self) -> I8: ...
    def to_i16_lossy(self) -> I16: ...
    def to_i32_lossy(self) -> I32: ...
    def to_i64_lossy(self) -> I64: ...
    def to_i128_lossy(self) -> I128: ...


class GraphKey:
    @staticmethod
    def from_view_key(view_key: ViewKey) -> GraphKey: ...
    @staticmethod
    def from_string(s: str) -> GraphKey: ...
    @property
    def sk_tag(self) -> Field: ...


class Group:
    @staticmethod
    def from_string(s: str) -> Group: ...
    @staticmethod
    def zero() -> Group: ...
    @staticmethod
    def generator() -> Group: ...
    @staticmethod
    def from_field(field: Field) -> Group: ...
    @staticmethod
    def from_bytes_le(bytes: bytes) -> Group: ...
    def to_x_coordinate(self) -> Field: ...
    def to_address(self) -> Address: ...
    def double(self) -> Group: ...
    def to_bytes_le(self) -> bytes: ...
    def add(self, other: Group) -> Group: ...
    def subtract(self, other: Group) -> Group: ...
    def negate(self) -> Group: ...
    def scalar_multiply(self, scalar: Scalar) -> Group: ...
    def __add__(self, other: Group) -> Group: ...
    def __sub__(self, other: Group) -> Group: ...
    def __neg__(self) -> Group: ...
    def __mul__(self, scalar: Scalar) -> Group: ...
    @staticmethod
    def random() -> Group: ...
    @staticmethod
    def from_bits_le(bits: list[bool]) -> Group: ...
    def to_bits_le(self) -> list[bool]: ...
    def to_fields(self) -> list[Field]: ...
    def to_plaintext(self) -> Plaintext: ...
    def to_field(self) -> Field: ...
    def to_scalar_lossy(self) -> Scalar: ...
    def to_boolean_lossy(self) -> Boolean: ...
    def to_u8_lossy(self) -> U8: ...
    def to_u16_lossy(self) -> U16: ...
    def to_u32_lossy(self) -> U32: ...
    def to_u64_lossy(self) -> U64: ...
    def to_u128_lossy(self) -> U128: ...
    def to_i8_lossy(self) -> I8: ...
    def to_i16_lossy(self) -> I16: ...
    def to_i32_lossy(self) -> I32: ...
    def to_i64_lossy(self) -> I64: ...
    def to_i128_lossy(self) -> I128: ...


class Identifier:
    @staticmethod
    def from_string(s: str) -> Identifier: ...


class I8:
    def __new__(cls, value: int) -> I8: ...
    @staticmethod
    def from_string(s: str) -> I8: ...
    @staticmethod
    def zero() -> I8: ...
    @staticmethod
    def one() -> I8: ...
    @staticmethod
    def random() -> I8: ...
    @staticmethod
    def from_bytes_le(bytes: bytes) -> I8: ...
    @staticmethod
    def from_bits_le(bits: list[bool]) -> I8: ...
    @staticmethod
    def from_field(f: Field) -> I8: ...
    @staticmethod
    def from_field_lossy(f: Field) -> I8: ...
    @staticmethod
    def from_fields(fields: list[Field]) -> I8: ...
    def __int__(self) -> int: ...
    def __add__(self, other: I8) -> I8: ...
    def __sub__(self, other: I8) -> I8: ...
    def __mul__(self, other: I8) -> I8: ...
    def __floordiv__(self, other: I8) -> I8: ...
    def __pow__(self, exp: U32, modulo: None = None) -> I8: ...
    def __neg__(self) -> I8: ...
    def add(self, other: I8) -> I8: ...
    def subtract(self, other: I8) -> I8: ...
    def multiply(self, other: I8) -> I8: ...
    def divide(self, other: I8) -> I8: ...
    def negate(self) -> I8: ...
    def abs_checked(self) -> I8: ...
    def abs_wrapped(self) -> I8: ...
    def add_wrapped(self, other: I8) -> I8: ...
    def sub_wrapped(self, other: I8) -> I8: ...
    def mul_wrapped(self, other: I8) -> I8: ...
    def div_wrapped(self, other: I8) -> I8: ...
    def rem(self, other: I8) -> I8: ...
    def rem_wrapped(self, other: I8) -> I8: ...
    def pow_u8(self, exp: U8) -> I8: ...
    def pow_u16(self, exp: U16) -> I8: ...
    def pow_u32(self, exp: U32) -> I8: ...
    def to_bytes_le(self) -> bytes: ...
    def to_bits_le(self) -> list[bool]: ...
    def to_field(self) -> Field: ...
    def to_scalar(self) -> Scalar: ...
    def to_plaintext(self) -> Plaintext: ...
    def to_boolean_lossy(self) -> Boolean: ...
    def to_u8_lossy(self) -> U8: ...
    def to_u16_lossy(self) -> U16: ...
    def to_u32_lossy(self) -> U32: ...
    def to_u64_lossy(self) -> U64: ...
    def to_u128_lossy(self) -> U128: ...
    def to_i8_lossy(self) -> I8: ...
    def to_i16_lossy(self) -> I16: ...
    def to_i32_lossy(self) -> I32: ...
    def to_i64_lossy(self) -> I64: ...
    def to_i128_lossy(self) -> I128: ...


class I16:
    def __new__(cls, value: int) -> I16: ...
    @staticmethod
    def from_string(s: str) -> I16: ...
    @staticmethod
    def zero() -> I16: ...
    @staticmethod
    def one() -> I16: ...
    @staticmethod
    def random() -> I16: ...
    @staticmethod
    def from_bytes_le(bytes: bytes) -> I16: ...
    @staticmethod
    def from_bits_le(bits: list[bool]) -> I16: ...
    @staticmethod
    def from_field(f: Field) -> I16: ...
    @staticmethod
    def from_field_lossy(f: Field) -> I16: ...
    @staticmethod
    def from_fields(fields: list[Field]) -> I16: ...
    def __int__(self) -> int: ...
    def __add__(self, other: I16) -> I16: ...
    def __sub__(self, other: I16) -> I16: ...
    def __mul__(self, other: I16) -> I16: ...
    def __floordiv__(self, other: I16) -> I16: ...
    def __pow__(self, exp: U32, modulo: None = None) -> I16: ...
    def __neg__(self) -> I16: ...
    def add(self, other: I16) -> I16: ...
    def subtract(self, other: I16) -> I16: ...
    def multiply(self, other: I16) -> I16: ...
    def divide(self, other: I16) -> I16: ...
    def negate(self) -> I16: ...
    def abs_checked(self) -> I16: ...
    def abs_wrapped(self) -> I16: ...
    def add_wrapped(self, other: I16) -> I16: ...
    def sub_wrapped(self, other: I16) -> I16: ...
    def mul_wrapped(self, other: I16) -> I16: ...
    def div_wrapped(self, other: I16) -> I16: ...
    def rem(self, other: I16) -> I16: ...
    def rem_wrapped(self, other: I16) -> I16: ...
    def pow_u8(self, exp: U8) -> I16: ...
    def pow_u16(self, exp: U16) -> I16: ...
    def pow_u32(self, exp: U32) -> I16: ...
    def to_bytes_le(self) -> bytes: ...
    def to_bits_le(self) -> list[bool]: ...
    def to_field(self) -> Field: ...
    def to_scalar(self) -> Scalar: ...
    def to_plaintext(self) -> Plaintext: ...
    def to_boolean_lossy(self) -> Boolean: ...
    def to_u8_lossy(self) -> U8: ...
    def to_u16_lossy(self) -> U16: ...
    def to_u32_lossy(self) -> U32: ...
    def to_u64_lossy(self) -> U64: ...
    def to_u128_lossy(self) -> U128: ...
    def to_i8_lossy(self) -> I8: ...
    def to_i16_lossy(self) -> I16: ...
    def to_i32_lossy(self) -> I32: ...
    def to_i64_lossy(self) -> I64: ...
    def to_i128_lossy(self) -> I128: ...


class I32:
    def __new__(cls, value: int) -> I32: ...
    @staticmethod
    def from_string(s: str) -> I32: ...
    @staticmethod
    def zero() -> I32: ...
    @staticmethod
    def one() -> I32: ...
    @staticmethod
    def random() -> I32: ...
    @staticmethod
    def from_bytes_le(bytes: bytes) -> I32: ...
    @staticmethod
    def from_bits_le(bits: list[bool]) -> I32: ...
    @staticmethod
    def from_field(f: Field) -> I32: ...
    @staticmethod
    def from_field_lossy(f: Field) -> I32: ...
    @staticmethod
    def from_fields(fields: list[Field]) -> I32: ...
    def __int__(self) -> int: ...
    def __add__(self, other: I32) -> I32: ...
    def __sub__(self, other: I32) -> I32: ...
    def __mul__(self, other: I32) -> I32: ...
    def __floordiv__(self, other: I32) -> I32: ...
    def __pow__(self, exp: U32, modulo: None = None) -> I32: ...
    def __neg__(self) -> I32: ...
    def add(self, other: I32) -> I32: ...
    def subtract(self, other: I32) -> I32: ...
    def multiply(self, other: I32) -> I32: ...
    def divide(self, other: I32) -> I32: ...
    def negate(self) -> I32: ...
    def abs_checked(self) -> I32: ...
    def abs_wrapped(self) -> I32: ...
    def add_wrapped(self, other: I32) -> I32: ...
    def sub_wrapped(self, other: I32) -> I32: ...
    def mul_wrapped(self, other: I32) -> I32: ...
    def div_wrapped(self, other: I32) -> I32: ...
    def rem(self, other: I32) -> I32: ...
    def rem_wrapped(self, other: I32) -> I32: ...
    def pow_u8(self, exp: U8) -> I32: ...
    def pow_u16(self, exp: U16) -> I32: ...
    def pow_u32(self, exp: U32) -> I32: ...
    def to_bytes_le(self) -> bytes: ...
    def to_bits_le(self) -> list[bool]: ...
    def to_field(self) -> Field: ...
    def to_scalar(self) -> Scalar: ...
    def to_plaintext(self) -> Plaintext: ...
    def to_boolean_lossy(self) -> Boolean: ...
    def to_u8_lossy(self) -> U8: ...
    def to_u16_lossy(self) -> U16: ...
    def to_u32_lossy(self) -> U32: ...
    def to_u64_lossy(self) -> U64: ...
    def to_u128_lossy(self) -> U128: ...
    def to_i8_lossy(self) -> I8: ...
    def to_i16_lossy(self) -> I16: ...
    def to_i32_lossy(self) -> I32: ...
    def to_i64_lossy(self) -> I64: ...
    def to_i128_lossy(self) -> I128: ...


class I64:
    def __new__(cls, value: int) -> I64: ...
    @staticmethod
    def from_string(s: str) -> I64: ...
    @staticmethod
    def zero() -> I64: ...
    @staticmethod
    def one() -> I64: ...
    @staticmethod
    def random() -> I64: ...
    @staticmethod
    def from_bytes_le(bytes: bytes) -> I64: ...
    @staticmethod
    def from_bits_le(bits: list[bool]) -> I64: ...
    @staticmethod
    def from_field(f: Field) -> I64: ...
    @staticmethod
    def from_field_lossy(f: Field) -> I64: ...
    @staticmethod
    def from_fields(fields: list[Field]) -> I64: ...
    def __int__(self) -> int: ...
    def __add__(self, other: I64) -> I64: ...
    def __sub__(self, other: I64) -> I64: ...
    def __mul__(self, other: I64) -> I64: ...
    def __floordiv__(self, other: I64) -> I64: ...
    def __pow__(self, exp: U32, modulo: None = None) -> I64: ...
    def __neg__(self) -> I64: ...
    def add(self, other: I64) -> I64: ...
    def subtract(self, other: I64) -> I64: ...
    def multiply(self, other: I64) -> I64: ...
    def divide(self, other: I64) -> I64: ...
    def negate(self) -> I64: ...
    def abs_checked(self) -> I64: ...
    def abs_wrapped(self) -> I64: ...
    def add_wrapped(self, other: I64) -> I64: ...
    def sub_wrapped(self, other: I64) -> I64: ...
    def mul_wrapped(self, other: I64) -> I64: ...
    def div_wrapped(self, other: I64) -> I64: ...
    def rem(self, other: I64) -> I64: ...
    def rem_wrapped(self, other: I64) -> I64: ...
    def pow_u8(self, exp: U8) -> I64: ...
    def pow_u16(self, exp: U16) -> I64: ...
    def pow_u32(self, exp: U32) -> I64: ...
    def to_bytes_le(self) -> bytes: ...
    def to_bits_le(self) -> list[bool]: ...
    def to_field(self) -> Field: ...
    def to_scalar(self) -> Scalar: ...
    def to_plaintext(self) -> Plaintext: ...
    def to_boolean_lossy(self) -> Boolean: ...
    def to_u8_lossy(self) -> U8: ...
    def to_u16_lossy(self) -> U16: ...
    def to_u32_lossy(self) -> U32: ...
    def to_u64_lossy(self) -> U64: ...
    def to_u128_lossy(self) -> U128: ...
    def to_i8_lossy(self) -> I8: ...
    def to_i16_lossy(self) -> I16: ...
    def to_i32_lossy(self) -> I32: ...
    def to_i64_lossy(self) -> I64: ...
    def to_i128_lossy(self) -> I128: ...


class I128:
    def __new__(cls, value: int) -> I128: ...
    @staticmethod
    def from_string(s: str) -> I128: ...
    @staticmethod
    def zero() -> I128: ...
    @staticmethod
    def one() -> I128: ...
    @staticmethod
    def random() -> I128: ...
    @staticmethod
    def from_bytes_le(bytes: bytes) -> I128: ...
    @staticmethod
    def from_bits_le(bits: list[bool]) -> I128: ...
    @staticmethod
    def from_field(f: Field) -> I128: ...
    @staticmethod
    def from_field_lossy(f: Field) -> I128: ...
    @staticmethod
    def from_fields(fields: list[Field]) -> I128: ...
    def __int__(self) -> int: ...
    def __add__(self, other: I128) -> I128: ...
    def __sub__(self, other: I128) -> I128: ...
    def __mul__(self, other: I128) -> I128: ...
    def __floordiv__(self, other: I128) -> I128: ...
    def __pow__(self, exp: U32, modulo: None = None) -> I128: ...
    def __neg__(self) -> I128: ...
    def add(self, other: I128) -> I128: ...
    def subtract(self, other: I128) -> I128: ...
    def multiply(self, other: I128) -> I128: ...
    def divide(self, other: I128) -> I128: ...
    def negate(self) -> I128: ...
    def abs_checked(self) -> I128: ...
    def abs_wrapped(self) -> I128: ...
    def add_wrapped(self, other: I128) -> I128: ...
    def sub_wrapped(self, other: I128) -> I128: ...
    def mul_wrapped(self, other: I128) -> I128: ...
    def div_wrapped(self, other: I128) -> I128: ...
    def rem(self, other: I128) -> I128: ...
    def rem_wrapped(self, other: I128) -> I128: ...
    def pow_u8(self, exp: U8) -> I128: ...
    def pow_u16(self, exp: U16) -> I128: ...
    def pow_u32(self, exp: U32) -> I128: ...
    def to_bytes_le(self) -> bytes: ...
    def to_bits_le(self) -> list[bool]: ...
    def to_field(self) -> Field: ...
    def to_scalar(self) -> Scalar: ...
    def to_plaintext(self) -> Plaintext: ...
    def to_boolean_lossy(self) -> Boolean: ...
    def to_u8_lossy(self) -> U8: ...
    def to_u16_lossy(self) -> U16: ...
    def to_u32_lossy(self) -> U32: ...
    def to_u64_lossy(self) -> U64: ...
    def to_u128_lossy(self) -> U128: ...
    def to_i8_lossy(self) -> I8: ...
    def to_i16_lossy(self) -> I16: ...
    def to_i32_lossy(self) -> I32: ...
    def to_i64_lossy(self) -> I64: ...
    def to_i128_lossy(self) -> I128: ...


class Literal:
    @staticmethod
    def parse(s: str) -> Literal: ...
    @staticmethod
    def from_address(address: Address) -> Literal: ...
    @staticmethod
    def from_field(field: Field) -> Literal: ...
    @staticmethod
    def from_group(group: Group) -> Literal: ...
    @staticmethod
    def from_scalar(scalar: Scalar) -> Literal: ...
    @staticmethod
    def from_signature(signature: Signature) -> Literal: ...
    @staticmethod
    def from_boolean(boolean: Boolean) -> Literal: ...
    @staticmethod
    def from_i8(value: I8) -> Literal: ...
    @staticmethod
    def from_i16(value: I16) -> Literal: ...
    @staticmethod
    def from_i32(value: I32) -> Literal: ...
    @staticmethod
    def from_i64(value: I64) -> Literal: ...
    @staticmethod
    def from_i128(value: I128) -> Literal: ...
    @staticmethod
    def from_u8(value: U8) -> Literal: ...
    @staticmethod
    def from_u16(value: U16) -> Literal: ...
    @staticmethod
    def from_u32(value: U32) -> Literal: ...
    @staticmethod
    def from_u64(value: U64) -> Literal: ...
    @staticmethod
    def from_u128(value: U128) -> Literal: ...
    def type_name(self) -> str: ...


class Locator:
    def __new__(cls, program_id: ProgramID, resource: Identifier) -> Locator: ...
    @staticmethod
    def from_string(s: str) -> Locator: ...
    @property
    def program_id(self) -> ProgramID: ...
    @property
    def name(self) -> Identifier: ...
    @property
    def network(self) -> Identifier: ...
    @property
    def resource(self) -> Identifier: ...


class Metadata:
    name: str
    locator: str
    prover: str
    verifier: str
    verifying_key: str
    @staticmethod
    def base_url() -> str: ...
    @staticmethod
    def bond_public() -> Metadata: ...
    @staticmethod
    def bond_validator() -> Metadata: ...
    @staticmethod
    def claim_unbond_public() -> Metadata: ...
    @staticmethod
    def fee_private() -> Metadata: ...
    @staticmethod
    def fee_public() -> Metadata: ...
    @staticmethod
    def inclusion() -> Metadata: ...
    @staticmethod
    def join() -> Metadata: ...
    @staticmethod
    def set_validator_state() -> Metadata: ...
    @staticmethod
    def split() -> Metadata: ...
    @staticmethod
    def transfer_private() -> Metadata: ...
    @staticmethod
    def transfer_private_to_public() -> Metadata: ...
    @staticmethod
    def transfer_public() -> Metadata: ...
    @staticmethod
    def transfer_public_as_signer() -> Metadata: ...
    @staticmethod
    def transfer_public_to_private() -> Metadata: ...
    @staticmethod
    def unbond_public() -> Metadata: ...


class MicroCredits:
    def __new__(cls, value: int) -> MicroCredits: ...
    def __int__(self) -> int: ...


class Network:
    @staticmethod
    def name() -> str: ...
    @staticmethod
    def id() -> int: ...
    @staticmethod
    def hash_psd2(input: list[Field]) -> Field: ...


class OfflineQuery:
    @staticmethod
    def new(block_height: int, state_root: str) -> OfflineQuery: ...
    @staticmethod
    def from_string(s: str) -> OfflineQuery: ...
    def add_block_height(self, block_height: int) -> None: ...
    def add_state_path(self, commitment: str, state_path: str) -> None: ...


class Pedersen64:
    def __new__(cls) -> Pedersen64: ...
    @staticmethod
    def setup(domain_separator: str) -> Pedersen64: ...
    def hash(self, input: list[bool]) -> Field: ...
    def commit(self, input: list[bool], randomizer: Scalar) -> Field: ...
    def commit_to_group(self, input: list[bool], randomizer: Scalar) -> Group: ...


class Pedersen128:
    def __new__(cls) -> Pedersen128: ...
    @staticmethod
    def setup(domain_separator: str) -> Pedersen128: ...
    def hash(self, input: list[bool]) -> Field: ...
    def commit(self, input: list[bool], randomizer: Scalar) -> Field: ...
    def commit_to_group(self, input: list[bool], randomizer: Scalar) -> Group: ...


class Plaintext:
    @staticmethod
    def from_string(s: str) -> Plaintext: ...
    @staticmethod
    def new_literal(literal: Literal) -> Plaintext: ...
    @staticmethod
    def new_struct(kv: list[tuple[Identifier, Plaintext]]) -> Plaintext: ...
    @staticmethod
    def new_array(kv: list[Plaintext]) -> Plaintext: ...
    def encrypt(self, address: Address, randomizer: Scalar) -> Ciphertext: ...
    def encrypt_symmetric(self, plaintext_view_key: Field) -> Ciphertext: ...
    def is_literal(self) -> bool: ...
    def is_struct(self) -> bool: ...
    def is_array(self) -> bool: ...
    def as_literal(self) -> "Literal": ...
    def as_struct(self) -> dict["Identifier", "Plaintext"]: ...
    def as_array(self) -> list["Plaintext"]: ...
    def find(self, path: list[str]) -> "Plaintext": ...
    def bytes(self) -> bytes: ...
    @staticmethod
    def from_bytes(bytes: bytes) -> "Plaintext": ...
    def to_bits_le(self) -> list[bool]: ...
    def to_bits_raw_le(self) -> list[bool]: ...
    def to_bits_raw_be(self) -> list[bool]: ...
    def to_bytes_raw_le(self) -> bytes: ...
    def to_bytes_raw_be(self) -> bytes: ...
    def to_fields(self) -> list["Field"]: ...
    @staticmethod
    def from_fields(fields: list["Field"]) -> "Plaintext": ...
    def to_fields_raw(self) -> list["Field"]: ...
    @property
    def plaintext_type(self) -> str: ...
    def to_python(self) -> object: ...


class Proof:
    @staticmethod
    def from_string(s: str) -> Proof: ...
    @staticmethod
    def from_bytes(bytes: bytes) -> Proof: ...
    def bytes(self) -> bytes: ...


class PrivateKeyCiphertext:
    @staticmethod
    def encrypt_private_key(private_key: "PrivateKey", secret: str) -> "PrivateKeyCiphertext": ...
    def decrypt_to_private_key(self, secret: str) -> "PrivateKey": ...
    @staticmethod
    def from_string(s: str) -> "PrivateKeyCiphertext": ...
    def __str__(self) -> str: ...
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self) -> int: ...


class Poseidon2:
    def __new__(cls) -> Poseidon2: ...
    @staticmethod
    def setup(domain_separator: str) -> Poseidon2: ...
    def hash(self, input: list[Field]) -> Field: ...
    def hash_many(self, input: list[Field], num_outputs: int) -> list[Field]: ...
    def hash_to_scalar(self, input: list[Field]) -> Scalar: ...
    def hash_to_group(self, input: list[Field]) -> Group: ...


class Poseidon4:
    def __new__(cls) -> Poseidon4: ...
    @staticmethod
    def setup(domain_separator: str) -> Poseidon4: ...
    def hash(self, input: list[Field]) -> Field: ...
    def hash_many(self, input: list[Field], num_outputs: int) -> list[Field]: ...
    def hash_to_scalar(self, input: list[Field]) -> Scalar: ...
    def hash_to_group(self, input: list[Field]) -> Group: ...


class Poseidon8:
    def __new__(cls) -> Poseidon8: ...
    @staticmethod
    def setup(domain_separator: str) -> Poseidon8: ...
    def hash(self, input: list[Field]) -> Field: ...
    def hash_many(self, input: list[Field], num_outputs: int) -> list[Field]: ...
    def hash_to_scalar(self, input: list[Field]) -> Scalar: ...
    def hash_to_group(self, input: list[Field]) -> Group: ...


class PrivateKey:
    @staticmethod
    def random() -> PrivateKey: ...
    @staticmethod
    def from_string(private_key: str) -> PrivateKey: ...
    @staticmethod
    def from_seed(seed: Field) -> PrivateKey: ...
    @property
    def address(self) -> Address: ...
    @property
    def view_key(self) -> ViewKey: ...
    @property
    def compute_key(self) -> ComputeKey: ...
    @property
    def seed(self) -> Field: ...
    def sign(self, message: bytes) -> "Signature": ...
    def sk_sig(self) -> "Scalar": ...
    def r_sig(self) -> "Scalar": ...
    @staticmethod
    def from_seed_unchecked(seed: list[int]) -> "PrivateKey": ...
    def sign_value(self, message: str) -> "Signature": ...
    def bytes(self) -> bytes: ...
    @staticmethod
    def from_bytes(bytes: bytes) -> "PrivateKey": ...
    @staticmethod
    def new_encrypted(secret: str) -> "PrivateKeyCiphertext": ...
    def to_ciphertext(self, secret: str) -> "PrivateKeyCiphertext": ...
    @staticmethod
    def from_private_key_ciphertext(ciphertext: "PrivateKeyCiphertext", secret: str) -> "PrivateKey": ...


class Process:
    @staticmethod
    def load() -> Process: ...
    def add_program(self, program: Program) -> None: ...
    def contains_program(self, program_id: ProgramID) -> bool: ...
    def get_proving_key(self, program_id: ProgramID, function_name: Identifier) -> ProvingKey: ...
    def insert_proving_key(self, program_id: ProgramID, function_name: Identifier, proving_key: ProvingKey) -> None: ...
    def get_verifying_key(self, program_id: ProgramID, function_name: Identifier) -> VerifyingKey: ...
    def insert_verifying_key(self, program_id: ProgramID, function_name: Identifier, verifying_key: VerifyingKey) -> None: ...
    def authorize(self, private_key: PrivateKey, program_id: ProgramID, function_name: Identifier, inputs: list[Value]) -> Authorization: ...
    def authorize_fee_private(self, private_key: PrivateKey, credits: RecordPlaintext, base_fee: int, priority_fee: int, deployment_or_execution_id: Field) -> Authorization: ...
    def authorize_fee_public(self, private_key: PrivateKey, base_fee: int, priority_fee: int, deployment_or_execution_id: Field) -> Authorization: ...
    def execute(self, authorization: Authorization) -> tuple[Response, Trace]: ...
    def verify_execution(self, execution: Execution) -> None: ...
    def verify_fee(self, fee: Fee, deployment_or_execution_id: Field) -> None: ...
    def execution_cost(self, execution: Execution) -> tuple[int, tuple[int, int]]: ...


class Program:
    @staticmethod
    def from_source(s: str) -> Program: ...
    @staticmethod
    def credits() -> Program: ...
    @property
    def id(self) -> ProgramID: ...
    @property
    def functions(self) -> list[Identifier]: ...
    @property
    def imports(self) -> list[ProgramID]: ...
    @property
    def source(self) -> str: ...
    def has_function(self, function_name: str) -> bool: ...
    def get_function_inputs(self, function_name: str) -> list[dict[str, Any]]: ...
    def get_mappings(self) -> list[dict[str, Any]]: ...
    def get_record_members(self, record_name: str) -> dict[str, Any]: ...
    def get_struct_members(self, struct_name: str) -> list[dict[str, Any]]: ...
    def address(self) -> Address: ...


class ProgramID:
    @staticmethod
    def from_string(s: str) -> ProgramID: ...
    @property
    def name(self) -> Identifier: ...
    @property
    def network(self) -> Identifier: ...
    def is_aleo(self) -> bool: ...


class ProvingKey:
    @staticmethod
    def from_string(s: str) -> ProvingKey: ...
    @staticmethod
    def from_bytes(bytes: bytes) -> ProvingKey: ...
    def bytes(self) -> bytes: ...
    def checksum(self) -> str: ...
    def is_bond_public_prover(self) -> bool: ...
    def is_bond_validator_prover(self) -> bool: ...
    def is_claim_unbond_public_prover(self) -> bool: ...
    def is_fee_private_prover(self) -> bool: ...
    def is_fee_public_prover(self) -> bool: ...
    def is_inclusion_prover(self) -> bool: ...
    def is_join_prover(self) -> bool: ...
    def is_set_validator_state_prover(self) -> bool: ...
    def is_split_prover(self) -> bool: ...
    def is_transfer_private_prover(self) -> bool: ...
    def is_transfer_private_to_public_prover(self) -> bool: ...
    def is_transfer_public_prover(self) -> bool: ...
    def is_transfer_public_as_signer_prover(self) -> bool: ...
    def is_transfer_public_to_private_prover(self) -> bool: ...
    def is_unbond_public_prover(self) -> bool: ...


class Query:
    @staticmethod
    def rest(url: str) -> Query: ...


class RecordCiphertext:
    @staticmethod
    def from_string(s: str) -> RecordCiphertext: ...
    def decrypt(self, view_key: ViewKey) -> RecordPlaintext: ...
    def is_owner(self, view_key: ViewKey) -> bool: ...
    @property
    def nonce(self) -> Group: ...
    def record_view_key(self, view_key: ViewKey) -> Field: ...
    def decrypt_with_record_view_key(self, record_view_key: Field) -> RecordPlaintext: ...
    @staticmethod
    def tag(graph_key: GraphKey, commitment: Field) -> Field: ...


class RecordPlaintext:
    @staticmethod
    def from_string(s: str) -> RecordPlaintext: ...
    @property
    def owner(self) -> str: ...
    @property
    def nonce(self) -> Group: ...
    @property
    def version(self) -> int: ...
    @property
    def microcredits(self) -> int: ...
    def commitment(self, program_id: ProgramID, record_name: Identifier, record_view_key: Field) -> Field: ...
    def record_view_key(self, view_key: ViewKey) -> Field: ...
    def tag(self, graph_key: GraphKey, commitment: Field) -> Field: ...
    def get_member(self, name: str) -> Plaintext: ...
    def serial_number(self, private_key: PrivateKey, program_id: ProgramID, record_identifier: Identifier, record_view_key: Field) -> Field: ...


class Response:
    @property
    def outputs(self) -> list[Value]: ...


class Scalar:
    @staticmethod
    def from_string(s: str) -> Scalar: ...
    @staticmethod
    def zero() -> Scalar: ...
    @staticmethod
    def one() -> Scalar: ...
    @staticmethod
    def random() -> Scalar: ...
    @staticmethod
    def from_bytes_le(bytes: bytes) -> Scalar: ...
    @staticmethod
    def from_bits_le(bits: list[bool]) -> Scalar: ...
    def to_bytes_le(self) -> bytes: ...
    def to_bits_le(self) -> list[bool]: ...
    def to_field(self) -> Field: ...
    def to_plaintext(self) -> Plaintext: ...
    def double(self) -> Scalar: ...
    def add(self, other: Scalar) -> Scalar: ...
    def subtract(self, other: Scalar) -> Scalar: ...
    def multiply(self, other: Scalar) -> Scalar: ...
    def divide(self, other: Scalar) -> Scalar: ...
    def pow(self, other: Scalar) -> Scalar: ...
    def negate(self) -> Scalar: ...
    def to_boolean(self) -> Boolean: ...
    def to_boolean_lossy(self) -> Boolean: ...
    def to_group(self) -> Group: ...
    def to_group_lossy(self) -> Group: ...
    def to_address(self) -> Address: ...
    def to_address_lossy(self) -> Address: ...
    def to_u8_lossy(self) -> U8: ...
    def to_u16_lossy(self) -> U16: ...
    def to_u32_lossy(self) -> U32: ...
    def to_u64_lossy(self) -> U64: ...
    def to_u128_lossy(self) -> U128: ...
    def to_i8_lossy(self) -> I8: ...
    def to_i16_lossy(self) -> I16: ...
    def to_i32_lossy(self) -> I32: ...
    def to_i64_lossy(self) -> I64: ...
    def to_i128_lossy(self) -> I128: ...
    def __pow__(self, other: Scalar) -> Scalar: ...
    def __neg__(self) -> Scalar: ...
    def __add__(self, other: Scalar) -> Scalar: ...
    def __sub__(self, other: Scalar) -> Scalar: ...
    def __mul__(self, other: Scalar) -> Scalar: ...
    def __truediv__(self, other: Scalar) -> Scalar: ...


class Signature:
    @property
    def challenge(self) -> Scalar: ...
    @property
    def compute_key(self) -> ComputeKey: ...
    @property
    def response(self) -> Scalar: ...
    @staticmethod
    def from_string(s: str) -> Signature: ...
    @staticmethod
    def sign(private_key: "PrivateKey", message: bytes) -> "Signature": ...
    def verify(self, address: "Address", message: bytes) -> bool: ...
    def to_address(self) -> "Address": ...
    def to_fields(self) -> list["Field"]: ...
    def to_bits_le(self) -> list[bool]: ...
    def bytes(self) -> bytes: ...
    @staticmethod
    def from_bytes(bytes: bytes) -> "Signature": ...
    @staticmethod
    def from_bits_le(bits: list[bool]) -> "Signature": ...
    def to_plaintext(self) -> "Plaintext": ...
    @staticmethod
    def sign_value(private_key: "PrivateKey", message: str) -> "Signature": ...
    def verify_value(self, address: "Address", message: str) -> bool: ...


class Trace:
    def is_fee(self) -> bool: ...
    def is_fee_private(self) -> bool: ...
    def is_fee_public(self) -> bool: ...
    def transitions(self) -> list[Transition]: ...
    def prove_execution(self, locator: str) -> Execution: ...
    def prove_fee(self) -> Fee: ...
    def prepare(self, query: Query) -> None: ...


class Transaction:
    @staticmethod
    def from_execution(execution: Execution, fee: Fee | None) -> Transaction: ...
    @staticmethod
    def from_json(json: str) -> Transaction: ...
    def to_json(self) -> str: ...
    @staticmethod
    def from_bytes(bytes: bytes) -> Transaction: ...
    def bytes(self) -> bytes: ...
    @property
    def id(self) -> str: ...
    @property
    def transaction_type(self) -> str: ...
    def is_deploy(self) -> bool: ...
    def is_execute(self) -> bool: ...
    def is_fee(self) -> bool: ...
    @property
    def base_fee_amount(self) -> int: ...
    @property
    def fee_amount(self) -> int: ...
    @property
    def priority_fee_amount(self) -> int: ...
    def records(self) -> list[tuple[Field, RecordCiphertext]]: ...
    def owned_records(self, view_key: ViewKey) -> list[RecordPlaintext]: ...
    def find_record(self, commitment: Field) -> RecordCiphertext | None: ...
    def contains_serial_number(self, serial_number: Field) -> bool: ...
    def contains_commitment(self, commitment: Field) -> bool: ...
    def execution(self) -> Execution | None: ...
    def transitions(self) -> list[Transition]: ...
    def deployed_program(self) -> Program | None: ...
    def verifying_keys(self) -> list[dict[str, Any]]: ...
    def summary(self) -> dict[str, Any]: ...


class Transition:
    @property
    def id(self) -> str: ...
    @property
    def program_id(self) -> ProgramID: ...
    @property
    def function_name(self) -> Identifier: ...
    def is_bond_public(self) -> bool: ...
    def is_unbond_public(self) -> bool: ...
    def is_fee_private(self) -> bool: ...
    def is_fee_public(self) -> bool: ...
    def is_split(self) -> bool: ...
    @staticmethod
    def from_json(json: str) -> Transition: ...
    def to_json(self) -> str: ...
    @staticmethod
    def from_bytes(bytes: bytes) -> Transition: ...
    def bytes(self) -> bytes: ...
    @property
    def tpk(self) -> Group: ...
    @property
    def tcm(self) -> Field: ...
    @property
    def scm(self) -> Field: ...
    def tvk(self, view_key: ViewKey) -> Field: ...
    def records(self) -> list[tuple[Field, RecordCiphertext]]: ...
    def owned_records(self, view_key: ViewKey) -> list[RecordPlaintext]: ...
    def find_record(self, commitment: Field) -> RecordCiphertext | None: ...
    def contains_commitment(self, commitment: Field) -> bool: ...
    def contains_serial_number(self, serial_number: Field) -> bool: ...
    def inputs(self) -> list[dict[str, Any]]: ...
    def outputs(self) -> list[dict[str, Any]]: ...
    def decrypt_transition(self, tvk: Field) -> Transition: ...


class U8:
    def __new__(cls, value: int) -> U8: ...
    @staticmethod
    def from_string(s: str) -> U8: ...
    @staticmethod
    def zero() -> U8: ...
    @staticmethod
    def one() -> U8: ...
    @staticmethod
    def random() -> U8: ...
    @staticmethod
    def from_bytes_le(bytes: bytes) -> U8: ...
    @staticmethod
    def from_bits_le(bits: list[bool]) -> U8: ...
    @staticmethod
    def from_field(f: Field) -> U8: ...
    @staticmethod
    def from_field_lossy(f: Field) -> U8: ...
    @staticmethod
    def from_fields(fields: list[Field]) -> U8: ...
    def __int__(self) -> int: ...
    def __add__(self, other: U8) -> U8: ...
    def __sub__(self, other: U8) -> U8: ...
    def __mul__(self, other: U8) -> U8: ...
    def __floordiv__(self, other: U8) -> U8: ...
    def __pow__(self, exp: U32, modulo: None = None) -> U8: ...
    def add(self, other: U8) -> U8: ...
    def subtract(self, other: U8) -> U8: ...
    def multiply(self, other: U8) -> U8: ...
    def divide(self, other: U8) -> U8: ...
    def add_wrapped(self, other: U8) -> U8: ...
    def sub_wrapped(self, other: U8) -> U8: ...
    def mul_wrapped(self, other: U8) -> U8: ...
    def div_wrapped(self, other: U8) -> U8: ...
    def rem(self, other: U8) -> U8: ...
    def rem_wrapped(self, other: U8) -> U8: ...
    def pow_u8(self, exp: U8) -> U8: ...
    def pow_u16(self, exp: U16) -> U8: ...
    def pow_u32(self, exp: U32) -> U8: ...
    def to_bytes_le(self) -> bytes: ...
    def to_bits_le(self) -> list[bool]: ...
    def to_field(self) -> Field: ...
    def to_scalar(self) -> Scalar: ...
    def to_plaintext(self) -> Plaintext: ...
    def to_boolean_lossy(self) -> Boolean: ...
    def to_u8_lossy(self) -> U8: ...
    def to_u16_lossy(self) -> U16: ...
    def to_u32_lossy(self) -> U32: ...
    def to_u64_lossy(self) -> U64: ...
    def to_u128_lossy(self) -> U128: ...
    def to_i8_lossy(self) -> I8: ...
    def to_i16_lossy(self) -> I16: ...
    def to_i32_lossy(self) -> I32: ...
    def to_i64_lossy(self) -> I64: ...
    def to_i128_lossy(self) -> I128: ...


class U16:
    def __new__(cls, value: int) -> U16: ...
    @staticmethod
    def from_string(s: str) -> U16: ...
    @staticmethod
    def zero() -> U16: ...
    @staticmethod
    def one() -> U16: ...
    @staticmethod
    def random() -> U16: ...
    @staticmethod
    def from_bytes_le(bytes: bytes) -> U16: ...
    @staticmethod
    def from_bits_le(bits: list[bool]) -> U16: ...
    @staticmethod
    def from_field(f: Field) -> U16: ...
    @staticmethod
    def from_field_lossy(f: Field) -> U16: ...
    @staticmethod
    def from_fields(fields: list[Field]) -> U16: ...
    def __int__(self) -> int: ...
    def __add__(self, other: U16) -> U16: ...
    def __sub__(self, other: U16) -> U16: ...
    def __mul__(self, other: U16) -> U16: ...
    def __floordiv__(self, other: U16) -> U16: ...
    def __pow__(self, exp: U32, modulo: None = None) -> U16: ...
    def add(self, other: U16) -> U16: ...
    def subtract(self, other: U16) -> U16: ...
    def multiply(self, other: U16) -> U16: ...
    def divide(self, other: U16) -> U16: ...
    def add_wrapped(self, other: U16) -> U16: ...
    def sub_wrapped(self, other: U16) -> U16: ...
    def mul_wrapped(self, other: U16) -> U16: ...
    def div_wrapped(self, other: U16) -> U16: ...
    def rem(self, other: U16) -> U16: ...
    def rem_wrapped(self, other: U16) -> U16: ...
    def pow_u8(self, exp: U8) -> U16: ...
    def pow_u16(self, exp: U16) -> U16: ...
    def pow_u32(self, exp: U32) -> U16: ...
    def to_bytes_le(self) -> bytes: ...
    def to_bits_le(self) -> list[bool]: ...
    def to_field(self) -> Field: ...
    def to_scalar(self) -> Scalar: ...
    def to_plaintext(self) -> Plaintext: ...
    def to_boolean_lossy(self) -> Boolean: ...
    def to_u8_lossy(self) -> U8: ...
    def to_u16_lossy(self) -> U16: ...
    def to_u32_lossy(self) -> U32: ...
    def to_u64_lossy(self) -> U64: ...
    def to_u128_lossy(self) -> U128: ...
    def to_i8_lossy(self) -> I8: ...
    def to_i16_lossy(self) -> I16: ...
    def to_i32_lossy(self) -> I32: ...
    def to_i64_lossy(self) -> I64: ...
    def to_i128_lossy(self) -> I128: ...


class U32:
    def __new__(cls, value: int) -> U32: ...
    @staticmethod
    def from_string(s: str) -> U32: ...
    @staticmethod
    def zero() -> U32: ...
    @staticmethod
    def one() -> U32: ...
    @staticmethod
    def random() -> U32: ...
    @staticmethod
    def from_bytes_le(bytes: bytes) -> U32: ...
    @staticmethod
    def from_bits_le(bits: list[bool]) -> U32: ...
    @staticmethod
    def from_field(f: Field) -> U32: ...
    @staticmethod
    def from_field_lossy(f: Field) -> U32: ...
    @staticmethod
    def from_fields(fields: list[Field]) -> U32: ...
    def __int__(self) -> int: ...
    def __add__(self, other: U32) -> U32: ...
    def __sub__(self, other: U32) -> U32: ...
    def __mul__(self, other: U32) -> U32: ...
    def __floordiv__(self, other: U32) -> U32: ...
    def __pow__(self, exp: U32, modulo: None = None) -> U32: ...
    def add(self, other: U32) -> U32: ...
    def subtract(self, other: U32) -> U32: ...
    def multiply(self, other: U32) -> U32: ...
    def divide(self, other: U32) -> U32: ...
    def add_wrapped(self, other: U32) -> U32: ...
    def sub_wrapped(self, other: U32) -> U32: ...
    def mul_wrapped(self, other: U32) -> U32: ...
    def div_wrapped(self, other: U32) -> U32: ...
    def rem(self, other: U32) -> U32: ...
    def rem_wrapped(self, other: U32) -> U32: ...
    def pow_u8(self, exp: U8) -> U32: ...
    def pow_u16(self, exp: U16) -> U32: ...
    def pow_u32(self, exp: U32) -> U32: ...
    def to_bytes_le(self) -> bytes: ...
    def to_bits_le(self) -> list[bool]: ...
    def to_field(self) -> Field: ...
    def to_scalar(self) -> Scalar: ...
    def to_plaintext(self) -> Plaintext: ...
    def to_boolean_lossy(self) -> Boolean: ...
    def to_u8_lossy(self) -> U8: ...
    def to_u16_lossy(self) -> U16: ...
    def to_u32_lossy(self) -> U32: ...
    def to_u64_lossy(self) -> U64: ...
    def to_u128_lossy(self) -> U128: ...
    def to_i8_lossy(self) -> I8: ...
    def to_i16_lossy(self) -> I16: ...
    def to_i32_lossy(self) -> I32: ...
    def to_i64_lossy(self) -> I64: ...
    def to_i128_lossy(self) -> I128: ...


class U64:
    def __new__(cls, value: int) -> U64: ...
    @staticmethod
    def from_string(s: str) -> U64: ...
    @staticmethod
    def zero() -> U64: ...
    @staticmethod
    def one() -> U64: ...
    @staticmethod
    def random() -> U64: ...
    @staticmethod
    def from_bytes_le(bytes: bytes) -> U64: ...
    @staticmethod
    def from_bits_le(bits: list[bool]) -> U64: ...
    @staticmethod
    def from_field(f: Field) -> U64: ...
    @staticmethod
    def from_field_lossy(f: Field) -> U64: ...
    @staticmethod
    def from_fields(fields: list[Field]) -> U64: ...
    def __int__(self) -> int: ...
    def __add__(self, other: U64) -> U64: ...
    def __sub__(self, other: U64) -> U64: ...
    def __mul__(self, other: U64) -> U64: ...
    def __floordiv__(self, other: U64) -> U64: ...
    def __pow__(self, exp: U32, modulo: None = None) -> U64: ...
    def add(self, other: U64) -> U64: ...
    def subtract(self, other: U64) -> U64: ...
    def multiply(self, other: U64) -> U64: ...
    def divide(self, other: U64) -> U64: ...
    def add_wrapped(self, other: U64) -> U64: ...
    def sub_wrapped(self, other: U64) -> U64: ...
    def mul_wrapped(self, other: U64) -> U64: ...
    def div_wrapped(self, other: U64) -> U64: ...
    def rem(self, other: U64) -> U64: ...
    def rem_wrapped(self, other: U64) -> U64: ...
    def pow_u8(self, exp: U8) -> U64: ...
    def pow_u16(self, exp: U16) -> U64: ...
    def pow_u32(self, exp: U32) -> U64: ...
    def to_bytes_le(self) -> bytes: ...
    def to_bits_le(self) -> list[bool]: ...
    def to_field(self) -> Field: ...
    def to_scalar(self) -> Scalar: ...
    def to_plaintext(self) -> Plaintext: ...
    def to_boolean_lossy(self) -> Boolean: ...
    def to_u8_lossy(self) -> U8: ...
    def to_u16_lossy(self) -> U16: ...
    def to_u32_lossy(self) -> U32: ...
    def to_u64_lossy(self) -> U64: ...
    def to_u128_lossy(self) -> U128: ...
    def to_i8_lossy(self) -> I8: ...
    def to_i16_lossy(self) -> I16: ...
    def to_i32_lossy(self) -> I32: ...
    def to_i64_lossy(self) -> I64: ...
    def to_i128_lossy(self) -> I128: ...


class U128:
    def __new__(cls, value: int) -> U128: ...
    @staticmethod
    def from_string(s: str) -> U128: ...
    @staticmethod
    def zero() -> U128: ...
    @staticmethod
    def one() -> U128: ...
    @staticmethod
    def random() -> U128: ...
    @staticmethod
    def from_bytes_le(bytes: bytes) -> U128: ...
    @staticmethod
    def from_bits_le(bits: list[bool]) -> U128: ...
    @staticmethod
    def from_field(f: Field) -> U128: ...
    @staticmethod
    def from_field_lossy(f: Field) -> U128: ...
    @staticmethod
    def from_fields(fields: list[Field]) -> U128: ...
    def __int__(self) -> int: ...
    def __add__(self, other: U128) -> U128: ...
    def __sub__(self, other: U128) -> U128: ...
    def __mul__(self, other: U128) -> U128: ...
    def __floordiv__(self, other: U128) -> U128: ...
    def __pow__(self, exp: U32, modulo: None = None) -> U128: ...
    def add(self, other: U128) -> U128: ...
    def subtract(self, other: U128) -> U128: ...
    def multiply(self, other: U128) -> U128: ...
    def divide(self, other: U128) -> U128: ...
    def add_wrapped(self, other: U128) -> U128: ...
    def sub_wrapped(self, other: U128) -> U128: ...
    def mul_wrapped(self, other: U128) -> U128: ...
    def div_wrapped(self, other: U128) -> U128: ...
    def rem(self, other: U128) -> U128: ...
    def rem_wrapped(self, other: U128) -> U128: ...
    def pow_u8(self, exp: U8) -> U128: ...
    def pow_u16(self, exp: U16) -> U128: ...
    def pow_u32(self, exp: U32) -> U128: ...
    def to_bytes_le(self) -> bytes: ...
    def to_bits_le(self) -> list[bool]: ...
    def to_field(self) -> Field: ...
    def to_scalar(self) -> Scalar: ...
    def to_plaintext(self) -> Plaintext: ...
    def to_boolean_lossy(self) -> Boolean: ...
    def to_u8_lossy(self) -> U8: ...
    def to_u16_lossy(self) -> U16: ...
    def to_u32_lossy(self) -> U32: ...
    def to_u64_lossy(self) -> U64: ...
    def to_u128_lossy(self) -> U128: ...
    def to_i8_lossy(self) -> I8: ...
    def to_i16_lossy(self) -> I16: ...
    def to_i32_lossy(self) -> I32: ...
    def to_i64_lossy(self) -> I64: ...
    def to_i128_lossy(self) -> I128: ...


class Value:
    @staticmethod
    def parse(s: str) -> "Value": ...
    @staticmethod
    def from_literal(literal: "Literal") -> "Value": ...
    @staticmethod
    def from_record_plaintext(record_plaintext: "RecordPlaintext") -> "Value": ...
    @staticmethod
    def from_plaintext(plaintext: "Plaintext") -> "Value": ...
    def to_plaintext(self) -> "Plaintext": ...
    def to_record_plaintext(self) -> "RecordPlaintext": ...
    def is_plaintext(self) -> bool: ...
    def is_record(self) -> bool: ...
    def is_future(self) -> bool: ...
    @property
    def value_type(self) -> str: ...
    def bytes(self) -> bytes: ...
    @staticmethod
    def from_bytes(bytes: bytes) -> "Value": ...
    def to_bits_le(self) -> list[bool]: ...
    def to_fields(self) -> list["Field"]: ...


class VerifyingKey:
    @staticmethod
    def from_string(s: str) -> VerifyingKey: ...
    @staticmethod
    def from_bytes(bytes: bytes) -> VerifyingKey: ...
    def bytes(self) -> bytes: ...
    def checksum(self) -> str: ...
    def num_constraints(self) -> int: ...
    @staticmethod
    def bond_public_verifier() -> VerifyingKey: ...
    @staticmethod
    def bond_validator_verifier() -> VerifyingKey: ...
    @staticmethod
    def claim_unbond_public_verifier() -> VerifyingKey: ...
    @staticmethod
    def fee_private_verifier() -> VerifyingKey: ...
    @staticmethod
    def fee_public_verifier() -> VerifyingKey: ...
    @staticmethod
    def inclusion_verifier() -> VerifyingKey: ...
    @staticmethod
    def join_verifier() -> VerifyingKey: ...
    @staticmethod
    def set_validator_state_verifier() -> VerifyingKey: ...
    @staticmethod
    def split_verifier() -> VerifyingKey: ...
    @staticmethod
    def transfer_private_verifier() -> VerifyingKey: ...
    @staticmethod
    def transfer_private_to_public_verifier() -> VerifyingKey: ...
    @staticmethod
    def transfer_public_verifier() -> VerifyingKey: ...
    @staticmethod
    def transfer_public_as_signer_verifier() -> VerifyingKey: ...
    @staticmethod
    def transfer_public_to_private_verifier() -> VerifyingKey: ...
    @staticmethod
    def unbond_public_verifier() -> VerifyingKey: ...
    def is_bond_public_verifier(self) -> bool: ...
    def is_bond_validator_verifier(self) -> bool: ...
    def is_claim_unbond_public_verifier(self) -> bool: ...
    def is_fee_private_verifier(self) -> bool: ...
    def is_fee_public_verifier(self) -> bool: ...
    def is_inclusion_verifier(self) -> bool: ...
    def is_join_verifier(self) -> bool: ...
    def is_set_validator_state_verifier(self) -> bool: ...
    def is_split_verifier(self) -> bool: ...
    def is_transfer_private_verifier(self) -> bool: ...
    def is_transfer_private_to_public_verifier(self) -> bool: ...
    def is_transfer_public_verifier(self) -> bool: ...
    def is_transfer_public_as_signer_verifier(self) -> bool: ...
    def is_transfer_public_to_private_verifier(self) -> bool: ...
    def is_unbond_public_verifier(self) -> bool: ...


class ViewKey:
    def decrypt(self, record_ciphertext: "RecordCiphertext") -> "RecordPlaintext": ...
    @staticmethod
    def from_string(s: str) -> "ViewKey": ...
    def is_owner(self, record_ciphertext: "RecordCiphertext") -> bool: ...
    @property
    def address(self) -> "Address": ...
    def to_scalar(self) -> "Scalar": ...
    def to_field(self) -> "Field": ...
    def bytes(self) -> bytes: ...
    @staticmethod
    def from_bytes(bytes: bytes) -> "ViewKey": ...
