# Generated by datamodel-code-generator — DO NOT EDIT.

from __future__ import annotations

from dataclasses import dataclass
from enum import Enum
from typing import Any


@dataclass
class ActiveSessionPayload:
    current: bool
    expires_at: int
    last_refreshed_at: int
    session_id: str
    started_at: int
    user_agent: str | None = None


@dataclass
class ActiveSessionsResponseDoc:
    data: list[ActiveSessionPayload]


class ActivityAction(Enum):
    create_pool = 'create_pool'


@dataclass
class AirdropRequest:
    address: str


@dataclass
class AirdropResult:
    amm_token_program: str
    amount: str
    status: str
    symbol: str
    error: str | None = None
    tx_id: str | None = None


@dataclass
class AirdropStartResult:
    job_id: str
    status: str


@dataclass
class ApiTokenCreateRequest:
    name: str
    expires_in_days: int | None = None


@dataclass
class ApiTokenCreatedResponse:
    created_at: str
    id: str
    name: str
    token: str
    token_prefix: str
    expires_at: str | None = None


@dataclass
class ApiTokenCreatedResponseDoc:
    data: ApiTokenCreatedResponse


@dataclass
class ApiTokenRevokeResponse:
    id: str
    revoked: bool


@dataclass
class ApiTokenRevokeResponseDoc:
    data: ApiTokenRevokeResponse


@dataclass
class ApiTokenRow:
    created_at: str
    id: str
    name: str
    token_prefix: str
    expires_at: str | None = None
    last_used_at: str | None = None
    revoked_at: str | None = None


@dataclass
class Asset:
    decimals: int
    id: str
    name: str
    symbol: str
    coinGeckoId: str | None = None


@dataclass
class AssetResponse:
    asset: Asset


@dataclass
class AuthTokenPayload:
    expires_at: int
    token: str


@dataclass
class AuthTokenResponseDoc:
    data: AuthTokenPayload


@dataclass
class BlockResponse:
    blockNumber: int
    blockTimestamp: int


@dataclass
class ChallengePayload:
    challenge_id: str
    message: str
    nonce: str


@dataclass
class ChallengeRequestDoc:
    address: str


@dataclass
class ChallengeResponseDoc:
    data: ChallengePayload


@dataclass
class ErrorResponseDoc:
    error: str
    code: str | None = None
    ref: str | None = None


@dataclass
class FeeBinding:
    fee_tier: int
    tick_spacing: int


@dataclass
class FeeTierDoc:
    created_at: str
    fee_tier: int
    id: str
    transaction: str
    tick_spacing: int | None = None


@dataclass
class FeeTierListResponseDoc:
    data: list[FeeTierDoc]


@dataclass
class GlobalConfigStatus:
    global_paused: bool
    pool_creation_is_open: bool


class GranularityDoc(Enum):
    field_1m = '1m'
    field_5m = '5m'
    field_15m = '15m'
    field_30m = '30m'
    field_1h = '1h'
    field_6h = '6h'
    field_12h = '12h'
    field_1d = '1d'


@dataclass
class InitializedTicksResponseDoc:
    data: list[int]


@dataclass
class LatestBlockResponse:
    block: BlockResponse


class LiveCompatibilityFailureCode(Enum):
    cache_unavailable = 'cache_unavailable'
    edition_mismatch = 'edition_mismatch'
    edition_unavailable = 'edition_unavailable'
    rate_limited = 'rate_limited'
    rpc_unavailable = 'rpc_unavailable'
    program_missing = 'program_missing'
    source_mismatch = 'source_mismatch'
    source_unavailable = 'source_unavailable'
    verification_timeout = 'verification_timeout'


class LiveCompatibilityStatus(Enum):
    compatible = 'compatible'
    incompatible = 'incompatible'
    unavailable = 'unavailable'


@dataclass
class LiveProgramObservation:
    source_sha256: str
    edition: int | None = None
    version: str | None = None


@dataclass
class LogoutAllResponse:
    address: str
    ended: bool
    ok: bool
    session_version: int


@dataclass
class LogoutAllResponseDoc:
    data: LogoutAllResponse


@dataclass
class LogoutResponse:
    ended: bool
    ok: bool
    session_id: str | None = None


@dataclass
class LogoutResponseDoc:
    data: LogoutResponse


@dataclass
class OhlcvDoc:
    c: str
    granularity: GranularityDoc
    h: str
    l: str
    o: str
    pool: str
    timestamp: int
    v: str


@dataclass
class OhlcvResponseDoc:
    data: list[OhlcvDoc]


@dataclass
class PaginationMeta:
    limit: int
    offset: int
    total: int


@dataclass
class Pair:
    asset0Id: str
    asset1Id: str
    dexKey: str
    feeBps: float
    id: str


@dataclass
class PairComplianceStatus:
    paused: bool
    token0: str
    token1: str


@dataclass
class PairResponse:
    pair: Pair


@dataclass
class PendingSwapOutputDoc:
    amount_out: str
    amount_remaining: str
    recipient: str
    token_in: str
    token_out: str


@dataclass
class PoolFeeProtocol:
    fee_protocol: int
    pool_key: str


@dataclass
class PoolStateDoc:
    created_at: str
    creator: str
    enabled: bool
    fee_percent: str
    id: str
    init_tx: str
    key: str
    token0: str
    token1: str


@dataclass
class PoolStats24hDoc:
    display_flipped: bool
    display_high_24h: str
    display_low_24h: str
    display_open_24h: str
    display_price: str
    high_24h: str
    liquidity: str
    low_24h: str
    open_24h: str
    price: str
    price_reversed: str
    volume_24h: str
    volume_7d: str
    change_24h_pct: str | None = None
    display_change_24h_pct: str | None = None
    fee_24h: str | None = None
    fee_7d: str | None = None
    reserve0: str | None = None
    reserve1: str | None = None


@dataclass
class PoolStats24hResponseDoc:
    data: PoolStats24hDoc


@dataclass
class PoolStatsDoc:
    active_tick: int
    fee_growth_global0_x_128: str
    fee_growth_global1_x_128: str
    fee_protocol: int
    id: str
    liquidity: str
    max_liquidity_per_tick: str
    next_init_above: int
    next_init_below: int
    pool: str
    price: str
    price_reversed: str
    protocol_fees0: str
    protocol_fees1: str
    tick_spacing: int


class PoolTradeFilterDoc(Enum):
    mint = 'mint'
    add_liquidity = 'add_liquidity'
    remove_liquidity = 'remove_liquidity'
    burn = 'burn'
    collect = 'collect'
    swap = 'swap'


class PoolTradeTypeDoc(Enum):
    mint = 'mint'
    add_liquidity = 'add_liquidity'
    remove_liquidity = 'remove_liquidity'
    burn = 'burn'
    collect = 'collect'
    swap = 'swap'
    swap_multi_hop = 'swap_multi_hop'


@dataclass
class PositionDoc:
    amount0: str
    amount1: str
    created_at: str
    created_transaction: str
    fee_growth_inside0_last_x_128: str | None
    fee_growth_inside1_last_x_128: str | None
    id: str
    is_burned: bool
    is_frozen: bool
    is_private: bool
    last_transaction: str
    liquidity: str
    pool: str
    tick_lower: int
    tick_upper: int
    token_id: str
    tokens_owed0: str
    tokens_owed1: str
    user: str
    created_transaction_hash: str | None = None
    frozen_at: str | None = None
    last_transaction_hash: str | None = None


@dataclass
class PositionListResponseDoc:
    data: list[PositionDoc]
    pagination: PaginationMeta


@dataclass
class ProtocolCapabilities:
    debug_api: bool
    faucet: bool
    freezelist_proofs: str
    protocol_config_websocket: bool
    token_admin: bool


@dataclass
class ProtocolFeeConfiguration:
    pool_fee_protocols: list[PoolFeeProtocol]
    registered_fee_tiers: list[int]
    registered_tick_spacings: list[int]
    valid_bindings: list[FeeBinding]


@dataclass
class ProtocolFreshness:
    ready_for_entry: bool
    confirmed_head: int | None = None
    indexed_block: int | None = None
    lag_blocks: int | None = None
    ready_for_quote: bool | None = None
    updated_at: str | None = None


@dataclass
class ProtocolPair:
    token0: str
    token1: str


@dataclass
class ProtocolProgram:
    program_id: str
    role: str
    source_sha256: str
    edition: int | None = None


@dataclass
class ProtocolRevisionPending:
    code: str
    current_revision: int
    error: str
    minimum_revision: int


@dataclass
class RebalanceTickState:
    fee_growth_outside0_x_128: str
    fee_growth_outside1_x_128: str
    tick: int


@dataclass
class ReferralActivityRequest:
    action: ActivityAction
    tx_id: str
    metadata: Any | None = None


@dataclass
class ReferralActivityResponse:
    recorded: bool


@dataclass
class ReferralActivityResponseDoc:
    data: ReferralActivityResponse


@dataclass
class ReferralAddressBatchRequest:
    blinded_addresses: list[str]
    code: str


@dataclass
class ReferralAddressBatchResponse:
    conflict: int
    duplicate: int
    recorded: int


@dataclass
class ReferralAddressBatchResponseDoc:
    data: ReferralAddressBatchResponse


@dataclass
class ReferralAdminCheckResponse:
    is_admin: bool


@dataclass
class ReferralAdminResponseDoc:
    data: ReferralAdminCheckResponse


@dataclass
class ReferralAdminTokenVolume:
    swap_count: int
    token: str
    volume: str


@dataclass
class ReferralAdminVolumeCode:
    code: str
    pending_count: int
    provisional: list[ReferralAdminTokenVolume]
    provisional_priced_swap_count: int
    provisional_swap_count: int
    provisional_unpriced_swap_count: int
    redemption_count: int
    rejected_count: int
    verified: list[ReferralAdminTokenVolume]
    verified_priced_swap_count: int
    verified_swap_count: int
    verified_unpriced_swap_count: int
    issued_to: str | None = None
    provisional_usd: str | None = None
    verified_usd: str | None = None


@dataclass
class ReferralAdminVolumeResponse:
    attributed_swap_count: int
    codes: list[ReferralAdminVolumeCode]
    unpriced_swap_count: int
    provisional_usd: str | None = None
    verified_usd: str | None = None


@dataclass
class ReferralAdminVolumeResponseDoc:
    data: ReferralAdminVolumeResponse


@dataclass
class ReferralCodeRow:
    code: str
    created_at: str
    redemption_count: int
    issued_to: str | None = None
    redeemed_at: str | None = None
    redeemed_by: str | None = None


@dataclass
class ReferralGenerateRequest:
    count: int


@dataclass
class ReferralGenerateResponse:
    codes: list[str]


@dataclass
class ReferralGenerateResponseDoc:
    data: ReferralGenerateResponse


@dataclass
class ReferralListResponse:
    available: int
    codes: list[ReferralCodeRow]
    redeemed: int
    redemptions: int
    total: int


@dataclass
class ReferralListResponseDoc:
    data: ReferralListResponse


@dataclass
class ReferralMyCodeResponse:
    code: str | None = None


@dataclass
class ReferralMyCodeResponseDoc:
    data: ReferralMyCodeResponse


@dataclass
class ReferralRedeemRequest:
    code: str


@dataclass
class ReferralRedeemResponse:
    code: str
    status: str


@dataclass
class ReferralRedeemResponseDoc:
    data: ReferralRedeemResponse


@dataclass
class ReferralSettingsResponse:
    codes_per_user: int
    codes_per_user_limit: int
    max_users: int | None = None


@dataclass
class ReferralSettingsResponseDoc:
    data: ReferralSettingsResponse


@dataclass
class ReferralStatusResponse:
    has_access: bool
    code: str | None = None
    my_code: str | None = None
    referred_by: str | None = None


@dataclass
class ReferralStatusResponseDoc:
    data: ReferralStatusResponse


@dataclass
class ReferralSwapClaimRequest:
    blinded_address: str
    code: str


@dataclass
class ReferralSwapClaimResponse:
    recorded: bool


@dataclass
class ReferralSwapClaimResponseDoc:
    data: ReferralSwapClaimResponse


@dataclass
class ReferralUpdateSettingsRequest:
    codes_per_user: int
    max_users: int | None = None


@dataclass
class Reserves:
    asset0: str
    asset1: str


@dataclass
class RevokeSessionPayload:
    current: bool
    ok: bool
    revoked: bool


@dataclass
class RevokeSessionResponseDoc:
    data: RevokeSessionPayload


@dataclass
class RevokeSessionsRequest:
    address: str


@dataclass
class RevokeSessionsResponse:
    refresh_tokens_revoked: int
    session_version: int


@dataclass
class RevokeSessionsResponseDoc:
    data: RevokeSessionsResponse


@dataclass
class RouteHopDoc:
    fee: str
    initialized_ticks: list[int]
    pool_key: str
    token_in: str
    token_out: str
    zero_for_one: bool
    active_tick: int | None = None
    liquidity: str | None = None
    price: str | None = None
    sqrt_price_raw: str | None = None
    tick_spacing: int | None = None


@dataclass
class RouteResultDoc:
    hops: list[RouteHopDoc]
    protocol_revision: int
    token_in: str
    token_out: str
    estimated_amount_out: str | None = None
    protocol_config_observed_block: int | None = None


@dataclass
class SessionPayload:
    address: str
    csrf_token: str
    expires_at: int
    session_version: int
    session_id: str | None = None


@dataclass
class SessionResponseDoc:
    data: SessionPayload


@dataclass
class SwapMetadata:
    fees0In: str | None = None
    fees1In: str | None = None


@dataclass
class TickLiquidityDoc:
    liquidity_net: str
    tick: int


@dataclass
class TickStatusDoc:
    exists: bool
    tick: int
    tick_mapping_key: str
    raw_value: str | None = None


@dataclass
class TokenComplianceStatus:
    allowed: bool
    paused: bool
    token_id: str


@dataclass
class TokenDoc:
    address: str
    decimals: int
    id: str
    name: str
    symbol: str
    amm_token_program: str | None = None
    image: str | None = None
    underlying_program: str | None = None
    underlying_token_id: str | None = None


@dataclass
class TokenListResponseDoc:
    data: list[TokenDoc]


@dataclass
class TopologyEdgeDoc:
    token0: str
    token1: str


@dataclass
class UsdcUsdQuote:
    corroborated: bool
    decimals: int
    price: str
    publishTime: int
    serverTime: int
    source: str
    validUntil: int


@dataclass
class VerifyRequestDoc:
    address: str
    challenge_id: str
    signature: str


@dataclass
class AirdropJob:
    results: list[AirdropResult]
    status: str
    total: int


@dataclass
class AirdropJobResponseDoc:
    data: AirdropJob


@dataclass
class AirdropStartResponseDoc:
    data: AirdropStartResult


@dataclass
class ApiTokenListResponse:
    tokens: list[ApiTokenRow]


@dataclass
class ApiTokenListResponseDoc:
    data: ApiTokenListResponse


@dataclass
class GlobalConfigResponseDoc:
    data: GlobalConfigStatus


@dataclass
class LiquidityDistributionResponseDoc:
    data: list[TickLiquidityDoc]


@dataclass
class LiveCompatibilityFailure:
    code: LiveCompatibilityFailureCode
    program_id: str | None = None


@dataclass
class PairComplianceResponseDoc:
    data: PairComplianceStatus


@dataclass
class PendingSwapDoc:
    is_multi_hop: bool
    is_private: bool
    output: PendingSwapOutputDoc
    swap_id: str
    swap_tx_hash: str
    token_in_info: TokenDoc | None = None
    token_out_info: TokenDoc | None = None


@dataclass
class PoolDebugInfoDoc:
    pool_key: str
    tick_statuses: list[TickStatusDoc]
    active_tick: int | None = None
    liquidity: str | None = None
    slot_raw: str | None = None
    sqrt_price: str | None = None
    tick_spacing: str | None = None


@dataclass
class PoolDebugResponseDoc:
    data: PoolDebugInfoDoc


@dataclass
class PoolResponseDoc(PoolStateDoc):
    display_flipped: bool
    base_token: TokenDoc | None = None
    quote_token: TokenDoc | None = None
    token0_info: TokenDoc | None = None
    token1_info: TokenDoc | None = None


@dataclass
class PoolStats24hBatchResponseDoc:
    data: dict[str, PoolStats24hDoc]


@dataclass
class PoolTradeDoc:
    amount0: str
    amount1: str
    executedAt: str
    id: str
    legIndex: int
    pool: str
    tradeType: PoolTradeTypeDoc
    transactionHash: str
    fee0: str | None = None
    fee1: str | None = None
    liquidityAfter: str | None = None
    protocolFee0: str | None = None
    protocolFee1: str | None = None
    sqrtPriceAfter: str | None = None
    tickAfter: int | None = None


@dataclass
class PoolTradesResponseDoc:
    data: list[PoolTradeDoc]
    pagination: PaginationMeta


@dataclass
class PoolWithStatsDoc(PoolStateDoc):
    display_flipped: bool
    base_token: TokenDoc | None = None
    quote_token: TokenDoc | None = None
    reserve0: str | None = None
    reserve1: str | None = None
    stats: PoolStatsDoc | None = None
    token0_info: TokenDoc | None = None
    token1_info: TokenDoc | None = None


@dataclass
class PoolWithStatsResponseDoc:
    data: PoolWithStatsDoc


@dataclass
class PositionWithOwedDoc:
    is_frozen: bool
    is_private: bool
    pool: str
    tick_lower: int
    tick_upper: int
    token_id: str
    tokens_owed0: str
    tokens_owed1: str
    frozen_at: str | None = None
    last_transaction_hash: str | None = None
    token0_info: TokenDoc | None = None
    token1_info: TokenDoc | None = None


@dataclass
class ProtocolControls:
    allowed_tokens: list[str]
    disabled_pools: list[str]
    global_paused: bool
    paused_pairs: list[ProtocolPair]
    paused_tokens: list[str]
    pool_creation_is_open: bool


@dataclass
class ProtocolDeployment:
    abi_version: int
    amm_start_block: int
    compatibility_fingerprint: str
    contract_ref: str
    contract_repository: str
    deployment_fingerprint: str
    freezelist_proof_version: str
    math_version: str
    network: str
    profile: str
    programs: dict[str, ProtocolProgram]
    protocol_version: int
    verified_at: str


@dataclass
class RebalanceState:
    fee_growth_global0_x_128: str
    fee_growth_global1_x_128: str
    lower: RebalanceTickState
    observed_block: int
    sqrt_price_x_128: str
    tick: int
    tick_lower_hint: int
    tick_spacing: int
    tick_upper_hint: int
    upper: RebalanceTickState


@dataclass
class RebalanceStateResponseDoc:
    data: RebalanceState


@dataclass
class RouteResponseDoc:
    data: RouteResultDoc


@dataclass
class RouteTopologyDoc:
    edges: list[TopologyEdgeDoc]
    max_hops: int
    protocol_revision: int
    protocol_config_observed_block: int | None = None


@dataclass
class RouteTopologyResponseDoc:
    data: RouteTopologyDoc


@dataclass
class SwapEvent:
    block: BlockResponse
    eventIndex: int
    eventType: str
    maker: str
    metadata: SwapMetadata
    pairId: str
    priceNative: str
    reserves: Reserves
    txnId: str
    txnIndex: int
    asset0In: str | None = None
    asset0Out: str | None = None
    asset1In: str | None = None
    asset1Out: str | None = None


@dataclass
class TokenComplianceResponseDoc:
    data: TokenComplianceStatus


@dataclass
class UnclaimedPayloadDoc:
    pending_swaps: list[PendingSwapDoc]
    positions_with_owed: list[PositionWithOwedDoc]


@dataclass
class UnclaimedResponseDoc:
    data: UnclaimedPayloadDoc


@dataclass
class EventsResponse:
    events: list[SwapEvent]


@dataclass
class LiveCompatibility:
    artifacts_checked: int
    checked_at: str
    failures: list[LiveCompatibilityFailure]
    observed_programs: dict[str, LiveProgramObservation]
    status: LiveCompatibilityStatus
    observed_artifact_vector_hash: str | None = None


@dataclass
class PoolListResponseDoc:
    data: list[PoolResponseDoc]
    pagination: PaginationMeta
    valuation: UsdcUsdQuote | None = None


@dataclass
class ProtocolStateResponse:
    capabilities: ProtocolCapabilities
    controls: ProtocolControls
    deployment: ProtocolDeployment
    fee_configuration: ProtocolFeeConfiguration
    freshness: ProtocolFreshness
    live_compatibility: LiveCompatibility
    revision: int
    changed_at: str | None = None
    observed_block: int | None = None
