# Generated by datamodel-code-generator — DO NOT EDIT.

from __future__ import annotations

from dataclasses import dataclass
from enum import Enum


@dataclass
class AccessCodeRow:
    code: str
    created_at: str
    redeemed_at: str | None = None
    redeemed_by: str | None = None


@dataclass
class AccessGenerateRequest:
    count: int


@dataclass
class AccessGenerateResponse:
    codes: list[str]


@dataclass
class AccessGenerateResponseDoc:
    data: AccessGenerateResponse


@dataclass
class AccessListResponse:
    available: int
    codes: list[AccessCodeRow]
    redeemed: int
    total: int


@dataclass
class AccessListResponseDoc:
    data: AccessListResponse


@dataclass
class AccessRedeemRequest:
    code: str


@dataclass
class AccessRedeemResponse:
    code: str
    status: str


@dataclass
class AccessRedeemResponseDoc:
    data: AccessRedeemResponse


@dataclass
class AccessStatusResponse:
    has_access: bool


@dataclass
class AccessStatusResponseDoc:
    data: AccessStatusResponse


@dataclass
class ActiveSessionPayload:
    current: bool
    expires_at: int
    last_refreshed_at: int
    session_id: str
    started_at: int
    user_agent: str | None = None


@dataclass
class ActiveSessionsResponseDoc:
    data: list[ActiveSessionPayload]


@dataclass
class AirdropRequest:
    address: str


@dataclass
class AirdropResult:
    amm_token_program: str
    amount: str
    status: str
    symbol: str
    error: str | None = None
    tx_id: str | None = None


@dataclass
class AirdropStartResult:
    job_id: str
    status: str


@dataclass
class ApiTokenCreateRequest:
    name: str
    expires_in_days: int | None = None


@dataclass
class ApiTokenCreatedResponse:
    created_at: str
    id: str
    name: str
    token: str
    token_prefix: str
    expires_at: str | None = None


@dataclass
class ApiTokenCreatedResponseDoc:
    data: ApiTokenCreatedResponse


@dataclass
class ApiTokenRevokeResponse:
    id: str
    revoked: bool


@dataclass
class ApiTokenRevokeResponseDoc:
    data: ApiTokenRevokeResponse


@dataclass
class ApiTokenRow:
    created_at: str
    id: str
    name: str
    token_prefix: str
    expires_at: str | None = None
    last_used_at: str | None = None
    revoked_at: str | None = None


@dataclass
class AuthTokenPayload:
    expires_at: int
    token: str


@dataclass
class AuthTokenResponseDoc:
    data: AuthTokenPayload


@dataclass
class ChallengePayload:
    challenge_id: str
    message: str
    nonce: str


@dataclass
class ChallengeRequestDoc:
    address: str


@dataclass
class ChallengeResponseDoc:
    data: ChallengePayload


@dataclass
class CreateTokenRequestDoc:
    address: str
    decimals: int
    name: str
    symbol: str
    amm_token_program: str | None = None


@dataclass
class DeployTokenRequest:
    decimals: int
    name: str
    recipient: str
    symbol: str
    supply: str | None = None


@dataclass
class DeployTokenResult:
    program_id: str
    recipient: str
    status: str


@dataclass
class ErrorResponseDoc:
    error: str
    ref: str | None = None


@dataclass
class FeeBinding:
    fee_tier: int
    tick_spacing: int


@dataclass
class FeeTierDoc:
    created_at: str
    fee_tier: int
    id: str
    transaction: str
    tick_spacing: int | None = None


@dataclass
class FeeTierListResponseDoc:
    data: list[FeeTierDoc]


@dataclass
class GlobalConfigStatus:
    global_paused: bool
    pool_creation_is_open: bool


class GranularityDoc(Enum):
    field_1m = '1m'
    field_5m = '5m'
    field_15m = '15m'
    field_30m = '30m'
    field_1h = '1h'
    field_6h = '6h'
    field_12h = '12h'
    field_1d = '1d'


@dataclass
class InitializedTicksResponseDoc:
    data: list[int]


class LiveCompatibilityFailureCode(Enum):
    cache_unavailable = 'cache_unavailable'
    edition_mismatch = 'edition_mismatch'
    edition_unavailable = 'edition_unavailable'
    rate_limited = 'rate_limited'
    rpc_unavailable = 'rpc_unavailable'
    source_mismatch = 'source_mismatch'
    source_unavailable = 'source_unavailable'
    verification_timeout = 'verification_timeout'


class LiveCompatibilityStatus(Enum):
    compatible = 'compatible'
    incompatible = 'incompatible'
    unavailable = 'unavailable'


@dataclass
class LogoutAllResponse:
    address: str
    ended: bool
    ok: bool
    session_version: int


@dataclass
class LogoutAllResponseDoc:
    data: LogoutAllResponse


@dataclass
class LogoutResponse:
    ended: bool
    ok: bool
    session_id: str | None = None


@dataclass
class LogoutResponseDoc:
    data: LogoutResponse


@dataclass
class MintTokenRequest:
    amm_token_program: str
    amount: str
    recipient: str


@dataclass
class MintTokenResult:
    status: str
    tx_id: str | None = None


@dataclass
class OhlcvDoc:
    c: str
    granularity: GranularityDoc
    h: str
    l: str
    o: str
    pool: str
    timestamp: int
    v: str


@dataclass
class OhlcvResponseDoc:
    data: list[OhlcvDoc]


@dataclass
class PaginationMeta:
    limit: int
    offset: int
    total: int


@dataclass
class PairComplianceStatus:
    paused: bool
    token0: str
    token1: str


@dataclass
class PendingSwapOutputDoc:
    amount_out: str
    amount_remaining: str
    recipient: str
    token_in: str
    token_out: str


@dataclass
class PoolFeeProtocol:
    fee_protocol: int
    pool_key: str


@dataclass
class PoolStateDoc:
    created_at: str
    creator: str
    enabled: bool
    fee_percent: str
    id: str
    init_tx: str
    key: str
    token0: str
    token1: str


@dataclass
class PoolStats24hDoc:
    display_flipped: bool
    display_high_24h: str
    display_low_24h: str
    display_open_24h: str
    display_price: str
    high_24h: str
    liquidity: str
    low_24h: str
    open_24h: str
    price: str
    price_reversed: str
    volume_24h: str
    change_24h_pct: str | None = None
    display_change_24h_pct: str | None = None


@dataclass
class PoolStats24hResponseDoc:
    data: PoolStats24hDoc


@dataclass
class PoolStatsDoc:
    active_tick: int
    fee_growth_global0_x_128: str
    fee_growth_global1_x_128: str
    fee_protocol: int
    id: str
    liquidity: str
    max_liquidity_per_tick: str
    next_init_above: int
    next_init_below: int
    pool: str
    price: str
    price_reversed: str
    protocol_fees0: str
    protocol_fees1: str
    tick_spacing: int


class PoolTradeFilterDoc(Enum):
    mint = 'mint'
    add_liquidity = 'add_liquidity'
    remove_liquidity = 'remove_liquidity'
    burn = 'burn'
    collect = 'collect'
    swap = 'swap'


class PoolTradeTypeDoc(Enum):
    mint = 'mint'
    add_liquidity = 'add_liquidity'
    remove_liquidity = 'remove_liquidity'
    burn = 'burn'
    collect = 'collect'
    swap = 'swap'
    swap_multi_hop = 'swap_multi_hop'


@dataclass
class PositionDoc:
    amount0: str
    amount1: str
    created_at: str
    created_transaction: str
    fee_growth_inside0_last_x_128: str
    fee_growth_inside1_last_x_128: str
    id: str
    is_burned: bool
    is_frozen: bool
    is_private: bool
    last_transaction: str
    liquidity: str
    pool: str
    tick_lower: int
    tick_upper: int
    token_id: str
    tokens_owed0: str
    tokens_owed1: str
    user: str
    created_transaction_hash: str | None = None
    frozen_at: str | None = None
    last_transaction_hash: str | None = None


@dataclass
class PositionListResponseDoc:
    data: list[PositionDoc]
    pagination: PaginationMeta


@dataclass
class PositionResponseDoc:
    data: PositionDoc


@dataclass
class ProtocolCapabilities:
    debug_api: bool
    faucet: bool
    freezelist_proofs: str
    protocol_config_websocket: bool
    token_admin: bool


@dataclass
class ProtocolFeeConfiguration:
    pool_fee_protocols: list[PoolFeeProtocol]
    registered_fee_tiers: list[int]
    registered_tick_spacings: list[int]
    valid_bindings: list[FeeBinding]


@dataclass
class ProtocolFreshness:
    ready_for_entry: bool
    confirmed_head: int | None = None
    indexed_block: int | None = None
    lag_blocks: int | None = None
    updated_at: str | None = None


@dataclass
class ProtocolPair:
    token0: str
    token1: str


@dataclass
class ProtocolProgram:
    program_id: str
    role: str
    source_sha256: str
    edition: int | None = None


@dataclass
class ProtocolRevisionPending:
    code: str
    current_revision: int
    error: str
    minimum_revision: int


@dataclass
class ReferralAdminCheckResponse:
    is_admin: bool


@dataclass
class ReferralAdminResponseDoc:
    data: ReferralAdminCheckResponse


@dataclass
class ReferralCodeRow:
    code: str
    created_at: str
    issued_to: str | None = None
    redeemed_at: str | None = None
    redeemed_by: str | None = None


@dataclass
class ReferralGenerateRequest:
    count: int


@dataclass
class ReferralGenerateResponse:
    codes: list[str]


@dataclass
class ReferralGenerateResponseDoc:
    data: ReferralGenerateResponse


@dataclass
class ReferralListResponse:
    available: int
    codes: list[ReferralCodeRow]
    redeemed: int
    total: int


@dataclass
class ReferralListResponseDoc:
    data: ReferralListResponse


@dataclass
class ReferralMyCodeRow:
    code: str
    redeemed_at: str | None = None
    redeemed_by: str | None = None


@dataclass
class ReferralMyCodesResponse:
    codes: list[ReferralMyCodeRow]
    quota: int


@dataclass
class ReferralMyCodesResponseDoc:
    data: ReferralMyCodesResponse


@dataclass
class ReferralRedeemRequest:
    code: str


@dataclass
class ReferralRedeemResponse:
    code: str
    status: str


@dataclass
class ReferralRedeemResponseDoc:
    data: ReferralRedeemResponse


@dataclass
class ReferralSettingsResponse:
    codes_per_user: int
    codes_per_user_limit: int
    max_users: int | None = None


@dataclass
class ReferralSettingsResponseDoc:
    data: ReferralSettingsResponse


@dataclass
class ReferralStatusResponse:
    has_access: bool
    code: str | None = None


@dataclass
class ReferralStatusResponseDoc:
    data: ReferralStatusResponse


@dataclass
class ReferralUpdateSettingsRequest:
    codes_per_user: int
    max_users: int | None = None


@dataclass
class RevokeSessionPayload:
    current: bool
    ok: bool
    revoked: bool


@dataclass
class RevokeSessionResponseDoc:
    data: RevokeSessionPayload


@dataclass
class RevokeSessionsRequest:
    address: str


@dataclass
class RevokeSessionsResponse:
    refresh_tokens_revoked: int
    session_version: int


@dataclass
class RevokeSessionsResponseDoc:
    data: RevokeSessionsResponse


@dataclass
class RouteHopDoc:
    fee: str
    initialized_ticks: list[int]
    pool_key: str
    token_in: str
    token_out: str
    zero_for_one: bool
    active_tick: int | None = None
    liquidity: str | None = None
    price: str | None = None
    sqrt_price_raw: str | None = None
    tick_spacing: int | None = None


@dataclass
class RouteResultDoc:
    hops: list[RouteHopDoc]
    protocol_revision: int
    token_in: str
    token_out: str
    estimated_amount_out: str | None = None
    protocol_config_observed_block: int | None = None


@dataclass
class SchemaField:
    description: str
    name: str
    type: str
    visibility: str
    fields: list[SchemaField] | None = None


@dataclass
class SessionPayload:
    address: str
    csrf_token: str
    expires_at: int
    session_version: int
    session_id: str | None = None


@dataclass
class SessionResponseDoc:
    data: SessionPayload


@dataclass
class SwapHopDoc:
    pool: str
    zero_for_one: bool


@dataclass
class TickLiquidityDoc:
    liquidity_net: str
    tick: int


@dataclass
class TickSpacingDoc:
    id: str
    tick_spacing: int


@dataclass
class TickSpacingListResponseDoc:
    data: list[TickSpacingDoc]


@dataclass
class TickStatusDoc:
    exists: bool
    tick: int
    tick_mapping_key: str
    raw_value: str | None = None


@dataclass
class TokenBalanceDoc:
    balance: str
    decimals: int
    name: str
    symbol: str
    token_address: str
    token_id: str


@dataclass
class TokenComplianceStatus:
    allowed: bool
    paused: bool
    token_id: str


@dataclass
class TokenDoc:
    address: str
    decimals: int
    id: str
    name: str
    symbol: str
    amm_token_program: str | None = None
    image: str | None = None
    underlying_program: str | None = None
    underlying_token_id: str | None = None


@dataclass
class TokenListResponseDoc:
    data: list[TokenDoc]


@dataclass
class TokenResponseDoc:
    data: TokenDoc


@dataclass
class VerifyRequestDoc:
    address: str
    challenge_id: str
    signature: str


@dataclass
class AirdropJob:
    results: list[AirdropResult]
    status: str
    total: int


@dataclass
class AirdropJobResponseDoc:
    data: AirdropJob


@dataclass
class AirdropStartResponseDoc:
    data: AirdropStartResult


@dataclass
class ApiTokenListResponse:
    tokens: list[ApiTokenRow]


@dataclass
class ApiTokenListResponseDoc:
    data: ApiTokenListResponse


@dataclass
class BalanceListResponseDoc:
    data: list[TokenBalanceDoc]


@dataclass
class DeployTokenResponseDoc:
    data: DeployTokenResult


@dataclass
class FunctionSchema:
    description: str
    function: str
    id: str
    inputs: list[SchemaField]
    program: str
    visibility: str
    follow_up: list[str] | None = None


@dataclass
class GlobalConfigResponseDoc:
    data: GlobalConfigStatus


@dataclass
class LiquidityDistributionResponseDoc:
    data: list[TickLiquidityDoc]


@dataclass
class LiveCompatibilityFailure:
    code: LiveCompatibilityFailureCode
    program_id: str | None = None


@dataclass
class MintTokenResponseDoc:
    data: MintTokenResult


@dataclass
class PairComplianceResponseDoc:
    data: PairComplianceStatus


@dataclass
class PendingSwapDoc:
    is_multi_hop: bool
    is_private: bool
    output: PendingSwapOutputDoc
    swap_id: str
    swap_tx_hash: str
    token_in_info: TokenDoc | None = None
    token_out_info: TokenDoc | None = None


@dataclass
class PoolDebugInfoDoc:
    pool_key: str
    tick_statuses: list[TickStatusDoc]
    active_tick: int | None = None
    liquidity: str | None = None
    slot_raw: str | None = None
    sqrt_price: str | None = None
    tick_spacing: str | None = None


@dataclass
class PoolDebugResponseDoc:
    data: PoolDebugInfoDoc


@dataclass
class PoolResponseDoc(PoolStateDoc):
    display_flipped: bool
    base_token: TokenDoc | None = None
    quote_token: TokenDoc | None = None
    token0_info: TokenDoc | None = None
    token1_info: TokenDoc | None = None


@dataclass
class PoolStats24hBatchResponseDoc:
    data: dict[str, PoolStats24hDoc]


@dataclass
class PoolTradeDoc:
    amount0: str
    amount1: str
    executedAt: str
    id: str
    pool: str
    tradeType: PoolTradeTypeDoc
    transactionHash: str


@dataclass
class PoolTradesResponseDoc:
    data: list[PoolTradeDoc]
    pagination: PaginationMeta


@dataclass
class PoolWithStatsDoc(PoolStateDoc):
    display_flipped: bool
    base_token: TokenDoc | None = None
    quote_token: TokenDoc | None = None
    stats: PoolStatsDoc | None = None
    token0_info: TokenDoc | None = None
    token1_info: TokenDoc | None = None


@dataclass
class PoolWithStatsResponseDoc:
    data: PoolWithStatsDoc


@dataclass
class PositionWithOwedDoc:
    is_frozen: bool
    is_private: bool
    pool: str
    tick_lower: int
    tick_upper: int
    token_id: str
    tokens_owed0: str
    tokens_owed1: str
    frozen_at: str | None = None
    last_transaction_hash: str | None = None
    token0_info: TokenDoc | None = None
    token1_info: TokenDoc | None = None


@dataclass
class ProtocolControls:
    allowed_tokens: list[str]
    disabled_pools: list[str]
    global_paused: bool
    paused_pairs: list[ProtocolPair]
    paused_tokens: list[str]
    pool_creation_is_open: bool


@dataclass
class ProtocolDeployment:
    abi_version: int
    amm_start_block: int
    contract_ref: str
    contract_repository: str
    deployment_fingerprint: str
    freezelist_proof_version: str
    math_version: str
    network: str
    profile: str
    programs: dict[str, ProtocolProgram]
    protocol_version: int
    verified_at: str


@dataclass
class RouteResponseDoc:
    data: RouteResultDoc


@dataclass
class SwapDoc:
    amount_remaining: str
    executed_at: str
    hops: list[SwapHopDoc]
    id: str
    input_amount: str
    input_token: str
    is_private: bool
    nonce: str
    output_amount: str
    output_token: str
    pool: str
    recipient: str
    swap_id: str
    transaction: str
    user: str
    claim_tx: str | None = None
    claimed_at: str | None = None
    input_token_info: TokenDoc | None = None
    output_token_info: TokenDoc | None = None
    trade: str | None = None


@dataclass
class SwapListResponseDoc:
    data: list[SwapDoc]
    pagination: PaginationMeta


@dataclass
class SwapResponseDoc:
    data: SwapDoc


@dataclass
class TokenComplianceResponseDoc:
    data: TokenComplianceStatus


@dataclass
class TradingSchemaListResponse:
    data: list[FunctionSchema]


@dataclass
class TradingSchemaResponse:
    data: FunctionSchema


@dataclass
class UnclaimedPayloadDoc:
    pending_swaps: list[PendingSwapDoc]
    positions_with_owed: list[PositionWithOwedDoc]


@dataclass
class UnclaimedResponseDoc:
    data: UnclaimedPayloadDoc


@dataclass
class LiveCompatibility:
    artifacts_checked: int
    checked_at: str
    failures: list[LiveCompatibilityFailure]
    status: LiveCompatibilityStatus


@dataclass
class PoolListResponseDoc:
    data: list[PoolResponseDoc]
    pagination: PaginationMeta


@dataclass
class ProtocolStateResponse:
    capabilities: ProtocolCapabilities
    controls: ProtocolControls
    deployment: ProtocolDeployment
    fee_configuration: ProtocolFeeConfiguration
    freshness: ProtocolFreshness
    live_compatibility: LiveCompatibility
    revision: int
    changed_at: str | None = None
    observed_block: int | None = None
