#!/usr/bin/env bash
# Refetch the DEX API's OpenAPI spec and regenerate the response models.
set -euo pipefail
cd "$(dirname "$0")"
BASE="${1:-https://amm-api.dev.provable.com}"
PYTHON="${PYTHON:-python3}"
curl -sf "${BASE}/openapi.json" | "$PYTHON" -m json.tool > amm_api.openapi.json
"$PYTHON" -m datamodel_code_generator \
  --input amm_api.openapi.json --input-file-type openapi \
  --output ../python/aleo_shield_swap/_api_models.py \
  --output-model-type dataclasses.dataclass \
  --target-python-version 3.10 \
  --use-standard-collections \
  --custom-file-header "# Generated by datamodel-code-generator — DO NOT EDIT."
echo "regenerated: amm_api.openapi.json + _api_models.py — review the git diff"
