#!/usr/bin/env bash
# Refetch the DEX API's OpenAPI spec and regenerate the response models.
set -euo pipefail
cd "$(dirname "$0")"
# The API is deployed per network on separate hosts; pass the network (or a
# full base URL) as $1. Never point this at amm-api.dev.provable.com — that
# host indexes the pre-migration shield_swap_v3.aleo.
TARGET="${1:-testnet}"
case "$TARGET" in
  mainnet) BASE="https://api.swap.shield.fi" ;;
  testnet) BASE="https://api.testnet.swap.shield.fi" ;;
  *)       BASE="$TARGET" ;;
esac
echo "fetching spec from $BASE"
PYTHON="${PYTHON:-python3}"
curl -sf "${BASE}/openapi.json" | "$PYTHON" -m json.tool > amm_api.openapi.json
"$PYTHON" -m datamodel_code_generator \
  --input amm_api.openapi.json --input-file-type openapi \
  --output ../python/aleo_shield_swap/_api_models.py \
  --output-model-type dataclasses.dataclass \
  --target-python-version 3.10 \
  --use-standard-collections \
  --custom-file-header "# Generated by datamodel-code-generator — DO NOT EDIT."
echo "regenerated: amm_api.openapi.json + _api_models.py — review the git diff"
